export const EXERCISES = [
    {
        "id": 0,
        "name": "BODYWEIGHT HIGH KNEES",
        "description": "MUSCLE GROUP:QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET WIDER THAN SHOULDER WIDTH APART. HOLD MEDICINE BALL IN FRONT OF YOU WITH ARMS FULLY EXTENDED. ADJUST FEET TO FACE SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF BY BENDING YOUR KNEES. YOUR BACK IS STRAIGHT THROUGHOUT THE WHOLE MOVEMENT. STOP WHEN YOUR THIGHS ARE NEARLY PARALLEL WITH THE GROUND. WHEN YOU RETURN THE STARTING POSITION, GENERATE ENERGY FROM YOUR LOWER BACK.",
        "images": ["bodyweight_high_knees_0.jpg", "bodyweight_high_knees_1.jpg"],
        "video": "BODYWEIGHT_HIGH_KNEES.mp4"
    },
    {
        "id": 1,
        "name": "PUSH UP ROTATING T EXTENSION",
        "description": "MUSCLE NAME: QUADRICEPS \n STEP 1. START IN A PUSHUP POSITION. KEEPING YOUR ARMS STRAIGHT AND YOUR CORE ENGAGED \n STEP 2. SHIFT YOUR WEIGHT ONTO YOUR LEFT ARM, ROTATE YOUR TORSO TO THE RIGHT, AND RAISE YOUR RIGHT ARM TOWARD THE CEILING SO THAT YOUR BODY FORMS A T. \n STEP 3. HOLD FOR THREE SECONDS, THEN RETURN TO START AND REPEAT ON THE OTHER SIDE. THAT'S ONE REP.",
        "images": ["push_up_rotating_t_extension_0.jpg", "push_up_rotating_t_extension_1.jpg"],
        "video": "PUSH_UP_ROTATING_T_EXTENSION.mp4"
    },
    {
        "id": 2,
        "name": "BODYWEIGHT PUSH-UP EXTENSION",
        "description": "MUSCLE GROUP: PRCTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS UNDER YOUR SHOULDERS. DISTANCE BETWEEN YOUR HANDS SHOULD BE NARROWER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. \n STEP 3: EXTEND ONE ARM AFTER EVERY TIME YOU COME UP. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_push_up_extension_0.jpg", "bodyweight_push_up_extension_1.jpg", "bodyweight_push_up_extension_2.jpg"],
        "video": "BODYWEIGHT_PUSH-UP_EXTENSION.mp4"
    },
    {
        "id": 3,
        "name": "BENT-LEG V-UP",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR, PUT YOUR ARMS AT THE SIDES. BENT YOUR KNEES OP AND HOLD THEM STILL. \n STEP 2: QUICKLY LIFT YOUR TORSO AS YOU PULL YOUR CHEST TO YOUR KNEES. KEEP YOUR ARMS PARALLEL TO THE FLOOR.",
        "images": ["bent_leg_v_up_0.jpg", "bent_leg_v_up_1.jpg"],
        "video": "BENT-LEG_V-UP.mp4"
    },
    {
        "id": 4,
        "name": "BODYWEIGHT HIGHT KNEE BOXING",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET CLOSE TO EACH OTHER. RUN IN PLACE WHILE LIFTING KNEE TO STOMACH LEVEL. KEEP THE DUMBBELL IN YOUR HANDS AND BOXING IN THE SAME TIME WITH MOVING YOUR LEGS. \n STEP 2: AS ONE FOOT LOWERS, THE OTHER RISES. THIS IS ONE REPETITION.",
        "images": ["bodyweight_hight_knee_boxing_0.jpg", "bodyweight_hight_knee_boxing_1.jpg"],
        "video": "BODYWEIGHT_HIGHT_KNEE_BOXING.mp4"
    },
    {
        "id": 5,
        "name": "BODYWEIGHT MOUNTAIN CLIMBERS",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR PALMS ON THE FLOOR. POSITION HANDS NEXT TO YOUR HEAD. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD \n STEP 2: BEND ONE LEG TOWARDS THE UPPER BODY. \n STEP 3: AS YOU BRING YOUR LEG BACK TO STARTING POSITION, BEND OTHER LEG TOWARDS THE UPPER BODY. THIS IS ONE REPETITION.",
        "images": ["bodyweight_mountain_climbers_0.jpg", "bodyweight_mountain_climbers_1.jpg"],
        "video": "BODYWEIGHT_MOUNTAIN_CLIMBERS.mp4"
    },
    {
        "id": 6,
        "name": "BODYWEIGHT JUMPING JACKS",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND TALL WITH YOUR BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDES. \n STEP 2: JUMP OUTWARD WITH YOUR FEET WIDER THAN SHOULDER WIDTH APART. AT THE SAME TIME, RAISE YOUR ARMS OVERHEAD. PAUSE BRIEFLY AND RETURN TO STARTING POSITION.",
        "images": ["bodyweight_jumping_jacks_0.jpg"],
        "video": "BODYWEIGHT_JUMPING_JACKS.mp4"
    },
    {
        "id": 7,
        "name": "BODYWEIGHT HIGHT KNEE JUMP",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND TALL WITH YOUR BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDES. \n STEP 2: BEND KNEES SLIGHTLY. \n STEP 3: JUMP UP AS HIGH AS YOU CAN. BRING YOUR KNEES TOWARD YOUR CHEST.",
        "images": ["bodyweight_hight_knee_jump_0.jpg", "bodyweight_hight_knee_jump_1.jpg", "bodyweight_hight_knee_jump_2.jpg", "bodyweight_hight_knee_jump_3.jpg"],
        "video": "BODYWEIGHT_HIGHT_KNEE_JUMP.mp4"
    },
    {
        "id": 8,
        "name": "BICYCLE",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LIE DOWN ON THE FLOOR. LIFT LEGS SO THAT YOUR THIGHS ARE PERPENDICULAR WITH THE GROUND. PUT HANDS BEHIND YOUR HEAD. \n STEP 2: MOVE LEFT ELBOW AND RIGHT LEG TOWARD THE BODY UNTIL THEY TOUCH \n STEP 3: MOVE LEFT ELBOW AND RIGHT LEG BACK TO STARTING POSITION. AT THE SAME TIME, MOVE RIGHT ELBOW AND LEFT LEG TOWARD THE BODY UNTIL THEY TOUCH. THIS IS ONE REPETITION.",
        "images": ["bodyweight_crunch_2_0.jpg", "bodyweight_crunch_2_1.jpg"],
        "video": "BODYWEIGHT_CRUNCH_2.mp4"
    },
    {
        "id": 9,
        "name": "BODYWEIGHT PUSH-UP",
        "description": "MUSCLE GROUP: PECTORALIS \n STEP 1: LIE DOWN CHEST RST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS NEXT TO YOUR LOWER CHEST. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. AT THE SAME TIME, BRING ONE KNEE TOWARDS YOUR ELBOW. HOLD FOR ONE SECOND \n STEP 3: RETURN TO STARTING POSITION. \n STEP 4: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. AT THE SAME TIME, BRING YOUR OTHER KNEE TOWARDS YOUR ELBOW. HOLD FOR ONE SECOND.",
        "images": ["bodyweight_push_up__0.jpg", "bodyweight_push_up__1.jpg", "bodyweight_push_up__2.jpg"],
        "video": "BODYWEIGHT_PUSH-UP.mp4"
    },
    {
        "id": 10,
        "name": "TOE TOUCH 3",
        "description": "MUSCLE: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. POSITION YOUR HANDS AND LEGS ON THE FLOOR. \n STEP 2: RAISE YOUR UPPER BODY UPWARD. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["reaching_leg_up_0.jpg", "reaching_leg_up_1.jpg", "reaching_leg_up_3.jpg"],
        "video": "REACHING_LEG-UP.mp4"
    },
    {
        "id": 11,
        "name": "PUSH-UP WALKING",
        "description": "MUSCLE GROUP: PECTORALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS NEXT TO YOUR LOWER CHEST. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. KEEP YOUR BACK AND LEGS STRAIGHT. \n STEP 2: WITHOUT MOVING YOUR ARMS, HOP TOWARD YOUR ARMS. HOP BACK TO STARTING POSITION AFTERWARD.",
        "images": ["push_up_walking_0.jpg", "push_up_walking_1.jpg", "push_up_walking_2.jpg"],
        "video": "PUSH-UP_WALKING.mp4"
    },
    {
        "id": 12,
        "name": "BODYWEIGHT PULL IN",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE ON THE FLOOR. PLACE HANDS UNDER YOUR HIP. EXTEND LEGS FULLY. SLIGHTLY RAISE LEGS. \n STEP 2: BEND LEGS TOWARDS YOUR UPPER BODY. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_pull_in_0.jpg", "bodyweight_pull_in_1.jpg"],
        "video": "BODYWEIGHT_PULL_IN.mp4"
    },
    {
        "id": 13,
        "name": "PLANK",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: POSITION LEGS STRAIGHT EXTENDED. WHILE KEEPING BACK STRAIGHT, PLACE FOREARMS ON THE FLOOR. YOUR FOREARMS ARE PERPENDICULAR WITH YOUR UPPER ARMS. HOLD FOR AS LONG AS YOU CAN.",
        "images": ["plank_0.jpg"],
        "video": "PLANK.mp4"
    },
    {
        "id": 14,
        "name": "BODYWEIGHT OPEN JUMP",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND TALL WITH YOUR BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDES. \n STEP 2: BEND KNEES SLIGHTLY. \n STEP 3: JUMP UP AS HIGH AS YOU CAN.",
        "images": ["bodyweight_open_jump_0.jpg", "bodyweight_open_jump_1.jpg"],
        "video": "BODYWEIGHT_OPEN_JUMP.mp4"
    },
    {
        "id": 15,
        "name": "BODYWEIGHT PUSH-UP TOUCH",
        "description": "MUSCLE GROUP: PRCTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS UNDER YOUR SHOULDERS. DISTANCE BETWEEN YOUR HANDS SHOULD BE NARROWER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. \n STEP 3: TOUCH YOUR OPPOSITE SHOULDER AFTER EVERY TIME YOU COME UP. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_push_up_touch_0.jpg", "bodyweight_push_up_touch_1.jpg", "bodyweight_push_up_touch_2.jpg", "bodyweight_push_up_touch_3.jpg"],
        "video": "BODYWEIGHT_PUSH-UP_TOUCH.mp4"
    },
    {
        "id": 16,
        "name": "BODYWEIGHT TOE TOUCH",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. LIFT LEGS UNTIL ONE LEG IS PERPENDICULAR WITH THE FLOOR. FULLY EXTEND YOUR ARMS ABOVE YOU. \n STEP 2: REACH FOR TOES WITH YOUR HANDS. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_toe_touch_0.jpg", "bodyweight_toe_touch_1.jpg"],
        "video": "BODYWEIGHT_TOE_TOUCH.mp4"
    },
    {
        "id": 17,
        "name": "DUMBBELL PUSH-UP ROW",
        "description": "MUSCLE GROUP: PECTORALIS \n STEP 1 HOLD ONTO TWO DUMBBELLS WITH NEUTRAL GRIP. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY THE DUMBBELLS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. \n STEP 3: RETURN TO STARTING POSITION. \n STEP 4: LIFT ONE DUMBBELL UP BY MOVING YOUR ELBOW UPWARD. YOUR HAND SHOULD MOVE IN A VERTICAL LINE. HOLD FOR ONE SECOND. \n STEP 5: RETURN TO STARTING POSITION. \n STEP 6: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. \n STEP 7: RETURN TO STARTING POSITION \n STEP 8: LIFT THE OTHER DUMBBELL UP BY MOVING YOUR ELBOW UPWARD. YOUR HAND SHOULD MOVE IN A VERTICAL LINE. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_push_up_row_0.jpg", "dumbbell_push_up_row_1.jpg", "dumbbell_push_up_row_2.jpg", "dumbbell_push_up_row_3.jpg"],
        "video": "DUMBBELL_PUSH-UP_ROW.mp4"
    },
    {
        "id": 18,
        "name": "BENCH DIP",
        "description": "MUSCLE GROUP: TRICEPS BRACHII \n STEP 1. PLACE YOUR PALMS ON A BENCH SO THEY FACE FORWARD, AND POSITION YOURSELF AS ILLUSTRATED. KEEP YOUR LEGS RELATIVELY STRAIGHT OUT IN FRONT, WITH BOTH HEELS FIRMLY ON THE FLOOR. STRAIGHTEN YOUR ARMS AND MOVE YOUR TORSO FORWARD SO THAT YOUR BEHIND AND BACK ARE JUST IN FRONT OF THE BENCH. \n STEP 2. BEND YOUR ARMS TO RIGHT ANGLES, LOWERING YOUR BEHIND TOWARD THE FLOOR AS SHOWN. YOU CAN MAKE THE EXERCISE EASIER BY BY BENDING YOUR KNEES AND MOVING YOUR FEET CLOSER TO THE BENCH.",
        "images": ["bench_dip_0.jpg", "bench_dip_1.jpg"],
        "video": "BENCH_DIP.mp4"
    },
    {
        "id": 19,
        "name": "DOUBLE SQUAT",
        "description": "MUSCLE GROUP:PRCTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS UNDER YOUR SHOULDERS. DISTANCE BETWEEN YOUR HANDS SHOULD BE NARROWER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. \n STEP 3: TOUCH YOUR OPPOSITE SHOULDER AFTER EVERY TIME YOU COME UP. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_hight_knee_jump_0.jpg", "bodyweight_hight_knee_jump_2.jpg"],
        "video": "DOUBLE_SQUAT.mp4"
    },
    {
        "id": 20,
        "name": "DUMBBELL SNATCH 1",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1: BEGIN BY SQUATTING LOWER OVER A DUMBBELL. MAINTAIN A LOCKED AND RIGID LOWER BACK AND HAVE YOUR FEET PLACED A SHOULDER WIDTH APART. \n STEP 2. GRASP THE DUMBBELL AND TIGHTEN THE ABDOMINAL MUSCLES. IN A RAPID AND US MOTION, LIFT THE DUMBBELL UPWARD UNTIL YOUR ARM IS STRAIGHT AND LOOKED, AS ILLUSTRATED. THE DUMBBELL SHOULD TRAVEL CLOSE TO THE BODY AND NOT SWING OUT OR AWAY. \n STEP 3. BRIEFLY HOLD IT ABOVE YOUR HEAD, THEN BRING IT DOWN TO THE STARTING POSITION.",
        "images": ["dumbbell_snatch_1_0.jpg", "dumbbell_snatch_1_1.jpg"],
        "video": "DUMBBELL_SNATCH_1.mp4"
    },
    {
        "id": 21,
        "name": "PUSH-UP DUMBBELL EXTENSION",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: HOLD ONTO TWO DUMBBELLS WITH NEUTRAL GRIP. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY THE DUMBBELLS AND TOES ARE ON THE FLOOR. EXTEND FULLY THE HAND WITH DUMBBELL. \n STEP 2: YOUR ARM HAS TO BE AT THE LEVEL OF YOURAYES. \n STEP 3: RETURN TO STARTING POSITION. \n STEP 4: LIFT ONE DUMBBELL UP BY MOVING YOUR ELBOW UPWARD. YOUR HAND SHOULD MOVE IN A VERTICAL LINE. HOLD FOR ONE SECOND. \n STEP 5: RETURN TO STARTING POSITION. \n STEP 6: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. \n STEP 7: RETURN TO STARTING POSITION \n STEP 8: LIFT THE OTHER DUMBBELL UP BY MOVING YOUR ELBOW UPWARD. YOUR HAND SHOULD MOVE IN A VERTICAL LINE. HOLD ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["push_up_dumbbell_extension_0.jpg", "push_up_dumbbell_extension_1.jpg", "push_up_dumbbell_extension_2.jpg", "push_up_dumbbell_extension_3.jpg"],
        "video": "PUSH-UP_DUMBBELL_EXTENSION.mp4"
    },
    {
        "id": 22,
        "name": "WEIGHTED TWIST RUSSIAN",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: SIT DOWN WITH YOUR FEET FLAT AND KNEES BENT. GRASP A WEIGHTED WITH BOTH HANDS. LEAN BACK SLIGHTLY AS YOU FULLY EXTEND YOUR ARMS STRAIGHT IN FRONT OF YOU. \n STEP 2: TWIST YOUR TORSO IN ONE DIRECTION. HOLD FOR ONE SECOND. \n STEP 3: RETURN TO STARTING POSITION. TWIST YOUR TORSO IN THE OTHER DIRECTION. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["weighted_twist_russian_0.jpg", "weighted_twist_russian_1.jpg"],
        "video": "WEIGHTED_TWIST_RUSSIAN.mp4"
    },
    {
        "id": 23,
        "name": "BODYWEIGHT HOP",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE PRONE ON THE FLOOR. RAISE YOURSELF UP SO THAT ONLY YOUR TOES AND HANDS ARE ON THE FLOOR. KEEP YOUR BACK STRAIGHT. \n STEP 2: WHILE KEEPING ARMS IN PLACE, HOP INWARD SO YOUR KNEES ARE CLOSE TO YOUR CHEST. HOP BACK TO STARTING POSITION.",
        "images": ["bodyweight_hop_0.jpg", "bodyweight_hop_1.jpg"],
        "video": "BODYWEIGHT_HOP.mp4"
    },
    {
        "id": 24,
        "name": "ROLLING PUSH-UP",
        "description": "MUSCLE GROUP: PECTORALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS NEXT TO YOUR LOWER CHEST. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. LIFT YOUR BEHIND UP IN THE AIR. ARMS SHOULD STRAIGHTEN OUT. \n STEP 2: PRETENDING THAT THERE IS AN IMAGINARY BAR TWO FEET FROM THE GROUND, GO UNDER THE BAR UNTIL YOUR ENTIRE UPPER BODY PASSED THE BAR. THE ELBOWS SHOULD BEND. ARMS STRAIGHTEN OUT AT THE END OF THE MOVEMENT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["rolling_push_up_0.jpg", "rolling_push_up_1.jpg", "rolling_push_up_2.jpg"],
        "video": "ROLLING_PUSH-UP.mp4"
    },
    {
        "id": 25,
        "name": "BENCH HIGH KNEE JUMP",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND TALL WITH YOUR BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDES. \n STEP 2: BEND KNEES SLIGHTLY. \n STEP 3: JUMP UP AS HIGH AS YOU CAN. BRING YOUR KNEES TOWARD YOUR CHEST.",
        "images": ["bench_high_knee_jump_0.jpg", "bench_high_knee_jump_1.jpg", "bench_high_knee_jump_2.jpg"],
        "video": "BENCH_HIGH_KNEE_JUMP.mp4"
    },
    {
        "id": 26,
        "name": "BODYWEIGHT LEG RAISE 2",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: SIT ON THE SIDE OF THE BENCH. HOLD ONTO THE SIDE OF THE BENCH WITH BOTH HANDS AT SHOULDER WIDTH. LIE BACK AND RAISE YOUR LEGS UNTIL YOU REACH A POSITION OF BALANCE. \n STEP 2: BEND YOUR KNEES TOWARDS YOUR UPPER BODY. AT THE SAME TIME, MOVE UPPER BODY FORWARD TO MAINTAIN POSITION OF BALANCE. HOLD FOR NONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_leg_raise_2_0.jpg", "bodyweight_leg_raise_2_1.jpg"],
        "video": "BODYWEIGHT_LEG_RAISE_2.mp4"
    },
    {
        "id": 27,
        "name": "MEDICINE BALL LUNGE 1",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD MEDICINE BALL OVERHEAD WITH ARMS FULLY EXTENDED. \n STEP 2: WHILE KEEPING YOUR BACK STRAIGHT, STEP FORWARD WITH ONE FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. STEP BACK AND RETURN TO STARTING POSITION. REPEAT WITH OTHER SIDE.",
        "images": ["medicine_ball_lunge_1_0.jpg", "medicine_ball_lunge_1_1.jpg"],
        "video": "MEDICINE_BALL_LUNGE_1.mp4"
    },
    {
        "id": 28,
        "name": "BODYWEIGHT PLANK LEG TOUCH 1",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE PRONE ON THE FLOOR. RAISE YOURSELF UP SO THAT ONLY YOUR TOES AND FOREARMS ARE ON THE FLOOR. KEEP YOUR BACK STRAIGHT. LIFT YOUR RIGHT LEG UP. HOLD FOR AS LONG AS POSSIBLE.",
        "images": ["bodyweight_plank_leg_touch_1_0.jpg", "bodyweight_plank_leg_touch_1_1.jpg", "bodyweight_plank_leg_touch_1_2.jpg"],
        "video": "BODYWEIGHT_PLANK_LEG_TOUCH.mp4"
    },
    {
        "id": 29,
        "name": "ALTERNATE HEEL TOUCH",
        "description":"MUSCLE GROUP: RECTUS ABDOMIN \n STEP 1: LAY DOWN ON THE FLOOR, BEND YOUR KNEES AND KEEP YOUR FEET 18-24 INCHES APART. KEEP YOUR ARMS STRAIGHT NEAR YOUR BODY. \n STEP 2: NOW CRUNCH OVER 3-4 INCHES AND TOUCH YOUR RIGHT HEEL ONCE. THAT CRUNCH BACK AND REPEAT IT. CRUNCH OVER AND TOUCH YOUR LEFT HEEL. WHILE CRUNCHING KEEP YOUR LOWER BACK ON THE FLOOR. REPEAT THIS REPEFIFION.",
        "images": ["alternate_heel_touch_0.jpg", "alternate_heel_touch_1.jpg"],
        "video": "ALTERNATE_HEEL_TOUCH.mp4"
    },
    {
        "id": 30,
        "name": "MODIFIED ELBOW TO KNEE CRUNCH",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LAI DOWN ON THE FLOOR, BEND YOUR LEGS AND PUT YOUR FEET ON THE GROUND. MOVE YOUR HANDS BEHIND YOUR EARS AND PUT YOUR ELBOWS OUT. CURVE YOUR RIGHT LEG UP AND REST YOUR FOOT ON YOUR LEFT KNEE. \n STEP 2: CRUNCH FORWARDS AND LIFT IT SIDEWAYS AND TRY TO TOUCH YOUR LEFT ELBOW TO YOUR RIGHT KNEE. THAN CRUNCH BACKWARDS, NOW SWAP AND CRUNCH FORWARD AND LIFT IT SIDEWAYS AND TRY TO TOUCH YOUR RIGHT ELBOW TO YOUR LEFT KNEE. REPEAT THIS.",
        "images": ["modified_elbow_to_knee_crunch_right_2.jpg", "modified_elbow_to_knee_crunch_right_3.jpg"],
        "video": "MODIFIED_ELBOW_TO_KNEE_CRUNCH_right.mp4"
    },
    {
        "id": 31,
        "name": "MODIFIED ELBOW TO KNEE CRUNCH SECOND SIDE",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LAI DOWN ON THE FLOOR, BEND YOUR LEGS AND PUT YOUR FEET ON THE GROUND. MOVE YOUR HANDS BEHIND YOUR EARS AND PUT YOUR ELBOWS OUT. CURVE YOUR RIGHT LEG UP AND REST YOUR FOOT ON YOUR LEFT KNEE. \n STEP 2: CRUNCH FORWARDS AND LIFT IT SIDEWAYS AND TRY TO TOUCH YOUR LEFT ELBOW TO YOUR RIGHT KNEE. THAN CRUNCH BACKWARDS, NOW SWAP AND CRUNCH FORWARD AND LIFT IT SIDEWAYS AND TRY TO TOUCH YOUR RIGHT ELBOW TO YOUR LEFT KNEE. REPEAT THIS.",
        "images": ["modified_elbow_to_knee_crunch_2.jpg", "modified_elbow_to_knee_crunch_3.jpg"],
        "video": "MODIFIED_ELBOW_TO_KNEE_CRUNCH.mp4"
    },
    {
        "id": 32,
        "name": "BODYWEIGHT PUSH-UP TOUCH 2",
        "description": "MUSCLE GROUP:QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART\n STEP 2: SQUAT DOWN AND TOUCH THE FLOOR WITH YOUR HANDS.\n STEP 3: JUMP BACKWARD TO A PUSHUP POSITION. ONLY YOUR HANDS AND TOES ARE TOUCHING THE GROUND\n STEP 4: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARD YOUR FEET. HOLD FOR ONE SECOND.\n STEP 5: FULL EXTEND YOUR ARMS TO GET BACK INTO PUSHUP POSITION.\n STEP 6: JUMP FORWARD SO THAT YOUR FEET NEAR YOUR HANDS. REMAIN IN A SQUAT POSITION. JUMP UPWARD WITH YOUR ARMS FULLY EXTENDED. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_push_up_touch_2_0.jpg", "bodyweight_push_up_touch_2_1.jpg"],
        "video": "BODYWEIGHT_PUSH-UP_TOUCH_2.mp4"
    },
    {
        "id": 33,
        "name": "DUMBBELL SNATCH-1 SECOND SIDE",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1: BEGIN BY SQUATTING LOWER OVER A DUMBBELL. MAINTAIN A LOCKED AND RIGID LOWER BACK AND HAVE YOUR FEET PLACED A SHOULDER WIDTH APART. \n STEP 2. GRASP THE DUMBBELL AND TIGHTEN THE ABDOMINAL MUSCLES. IN A RAPID AND US MOTION, LIFT THE DUMBBELL UPWARD UNTIL YOUR ARM IS STRAIGHT AND LOOKED, AS ILLUSTRATED. THE DUMBBELL SHOULD TRAVEL CLOSE TO THE BODY AND NOT SWING OUT OR AWAY. \n STEP 3. BRIEFLY HOLD IT ABOVE YOUR HEAD, THEN BRING IT DOWN TO THE STARTING POSITION.",
        "images": ["dumbbell_snatch_1_right_0.jpg", "dumbbell_snatch_1_right_1.jpg"],
        "video": "DUMBBELL_SNATCH-1_right.mp4"
    },
    {
        "id": 34,
        "name": "BODYWEIGHT BURPEE",
        "description": "MUSCLE GROUP:QUADRICEPS \n STEP 1: STAND STRAIGHT FEET SHOULDER WIDTH APART. ADJUST FEET TO FACE SLIGHTLY OUTWARD.\n STEP 2: LOWER YOURSELF BY BENDING YOUR KNEES. YOUR BACK SHOULD BE STRAIGHT THROUGHOUT THE WHOLE MOVEMENT. STOP WHEN YOUR THIGHS ARE PARALLEL WITH THE GROUND. WHEN YOU RETURN THE STARTING POSITION, GENERATE ENERGY FROM YOUR LOWER BACK.",
        "images": ["bodyweight_burpee_0.jpg", "bodyweight_burpee_1.jpg"],
        "video": "BODYWEIGHT_BURPEE.mp4"
    },
    {
        "id": 35,
        "name": "MEDICINE BALL TWIST",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: SIT DOWN WITH YOUR LEGS FULLY EXTEND IN FRONT OF YOU. HOLD A MEDICINE BALL WITH BOTH HANDS. LEAN BACK UNTIL YOU ARE BALANCING ON YOUR TAILBONE. \n STEP 2: TWIST YOUR TORSO IN ONE DIRECTION. HOLD FOR ONE SECOND. \n STEP 3: RETURN TO STARTING POSITION. \n STEP 4: TWIST YOUR TORSO IN THE OTHER DIRECTION. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["medicine_ball_twist_0.jpg", "medicine_ball_twist_1.jpg"],
        "video": "MEDICINE_BALL_TWIST.mp4"
    },
    {
        "id": 36,
        "name": "BODYWEIGHT LEG RAISE 3",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLAT BENCH. PLACE HANDS ON THE BENCH. EXTEND LEGS FULLY. \n STEP 2: RALSE AND BEND LEGS TOWARDS YOUR UPPER BODY. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_leg_raise_3_0.jpg", "bodyweight_leg_raise_3_1.jpg"],
        "video": "BODYWEIGHT_LEG_RAISE_3.mp4"
    },
    {
        "id": 37,
        "name": "OBLIQUE V-UP SECOND SIDE",
        "description": "MUSCLE NAME: OBLIQUES \n STEP 1: LIE ON YOUR SIDE WITH YOUR BODY IN A STRAIGHT LINE AND YOUR ARMS CROSSED AGAINST YOUR CHEST. \n STEP 2: LIFT YOUR LEGS OFF THE FLOOR, MAKING SURE TO KEEP THEM TIGHTLY BOUND CONTRACTING, EVEN THOUGHT THERE ISN'T TOO MUCH MOTION INVOLVED. \n STEP 3: PAUSE, THEN SLOWLY RETURN TO THE STARTING POSITION. REPEAT AS MANY TIMES AS NEEDED THEN SWITCH SIDES.",
        "images": ["oblique_v_up_right_0.jpg", "oblique_v_up_right_1.jpg"],
        "video": "OBLIQUE_V-UP_right.mp4"
    },
    {
        "id": 38,
        "name": "DUMBBELL DEADLIFT",
        "description": "MUSCLE GROUP: LOWER BACK \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELLS OF YOUR THIGHS WITH OVERHAND GRIP. LOWER YOURSELF UNTIL DUMBBELLS ARE AROUND SHIN LEVEL. KNEES BEND SLIGHTLY. KEEP CHEST STICKING OUTWARD AND YOUR BACK STRAIGHT. \n STEP 2: LIFT YOURSELF UP UNTIL YOUR ARE STANDING STRAIGHT. KEEP YOUR CHEST OUT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_deadlift_0.jpg", "dumbbell_deadlift_1.jpg"],
        "video": "DUMBBELL_DEADLIFT.mp4"
    },
    {
        "id": 39,
        "name": "BARBELL GOOD MORNING",
        "description": "MUSCLE GROUP: HAMSTRINGS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. PLACE BARBELL ON THE BACK OF YOUR SHOULDERS. HOLD BARBELL WITH OVERHAND GRIP. DISTANCE BETWEEN YOUR HANDS SHOULD BE WIDER THAN SHOULDER WIDTH APART. ADJUST FEET TO POINT SLIGHTLY OUTWARD. \n STEP 2: KEEP BACK STRAIGHT AND BEND UPPER BODY UNTIL IT IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["barbell_good_morning_0.jpg", "barbell_good_morning_1.jpg"],
        "video": "BARBELL_GOOD_MORNING.mp4"
    },
    {
        "id": 40,
        "name": "DUMBBELL ROW",
        "description": "MUSCLE GROUP: LATISSIMUS DORSI \n STEP 1: BEND YOUR KNEES SLIGHTLY. KEEP BACK BENT AND STRAIGHT. HOLD DUMBBELLS TO YOUR SIDE WITH NEUTRAL GRIP. \n STEP 2: RAISE THE DUMBBELLS VERTICALLY TOWARDS YOUR CHEST. REFRAIN FROM FLARING YOUR ELBOW OUT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_row_0.jpg", "dumbbell_row_1.jpg"],
        "video": "DUMBBELL_ROW.mp4"
    },
    {
        "id": 41,
        "name": "BODYWEIGHT SUPERMAN 3",
        "description": "MUSCLE GROUP: LOWER BACK \n STEP 1: LIE PRONE ON THE FLOOR. KEEP YOUR ARMS BEHIND OF YOU HEAD. \n STEP 2: RAISE YOUR LEGS AND UPPER BODY TOWARDS THE CEILING. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION",
        "images": ["bodyweight_superman_3_0.jpg", "bodyweight_superman_3_1.jpg"],
        "video": "BODYWEIGHT_SUPERMAN_3.mp4"
    },
    {
        "id": 42,
        "name": "ARMY PUSH UP",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS NEXT TO YOUR LOWER CHEST. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD \n STEP 2: ALIGN YOUR SHOULDERS WITH YOUR HANDS, AND LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["army_push_up_0.jpg", "army_push_up_1.jpg", "army_push_up_2.jpg", "army_push_up_3.jpg"],
        "video": "ARMY_PUSH_UP.mp4"
    },
    {
        "id": 43,
        "name": "CURL",
        "description": "MUSCLE GROUP: BICEBS BRACHII \n STEP 1: STAND WITH FEET ABOUT HIP-WIDTH APART, ABS ENGAGED AS YOU HOLD MEDIUM HEAVY DUMBBELLS IN FRONT OF THE THIGHS. SQUEEZE THE BICEPS AND BEND THE ARMS, CURLING THE WEIGHTS UP TOWARDS THE SHOULDERS. \n STEP 2: KEEP THE ELBOWS STATIONARY AND ONLY BRING THE WEIGHT AS HIGH AS YOU CAN WITHOUT MOVING THE ELBOWS. SLOWLY LOWER THE WEIGHTS, KEEPING A SLIGHT BEND IN THE ELBOWS AT THE BOTTOM (E.G., DON'T LOCK THE JOINTS AND TRY TO KEEP TENSION ON)",
        "images": ["curl_1.jpg", "curl_2.jpg"],
        "video": "CURL.mp4"
    },
    {
        "id": 44,
        "name": "BODYWEIGHT LUNGE SIDE",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD YOUR ARMS IN THE FRONT OF YOUR CHEST. \n STEP 2: WHILE KEEPING YOUR BACK STRAIGHT, STEP TO YOUR SIDE WITH ONE FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. THE BACK FOOT PIVOTS BUT STAYS IN POSITION. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_lunge_side_1.jpg", "bodyweight_lunge_side_2.jpg"],
        "video": "BODYWEIGHT_LUNGE_SIDE.mp4"
    },
    {
        "id": 45,
        "name": "DUMBBELL LUNGE 2",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELLS AT YOUR SIDES WITH NEUTRAL GRIP. \n STEP 2: WHILE KEEPING YOUR BACK STRAIGHT, STEP FORWARD WITH ONE FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. STEP BACK AND RETURN TO STARTING POSITION.",
        "images": ["dumbbell_lunge_2_0.jpg", "dumbbell_lunge_2_1.jpg"],
        "video": "DUMBBELL_LUNGE_2.mp4"
    },
    {
        "id": 46,
        "name": "BODYWEIGHT LUNGE SIDE SECOND SIDE",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD YOUR ARMS IN THE FRONT OF YOUR CHEST. \n STEP 2: WHILE KEEPING YOUR BACK STRAIGHT, STEP TO YOUR SIDE WITH ONE FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. THE BACK FOOT PIVOTS BUT STAYS IN POSITION. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_lunge_side_right_1.jpg", "bodyweight_lunge_side_right_2.jpg"],
        "video": "BODYWEIGHT_LUNGE_SIDE_right.mp4"
    },
    {
        "id": 47,
        "name": "BENCH SIDE JUMP",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND TALL WITH YOUR BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDES. \n STEP 2: BEND KNEES SLIGHTLY. MOVE FROM TO THE SIDES SUPPORTING YOUR LEG ON THE BENCH. \n STEP 3: JUMP UP AS HIGH AS YOU CAN. BRING YOUR KNEES TOWARD YOUR CHEST.",
        "images": ["bench_side_jump_0.jpg", "bench_side_jump_1.jpg"],
        "video": "BENCH_SIDE_JUMP.mp4"
    },
    {
        "id": 48,
        "name": "DUMBBELL CLEAN AND JERK",
        "description": "MUSCLE GROUP: HAMSTRINGS \n STEP 1: SQUAT DOWN. HOLD DUMBBELLS UNDER YOU WITH NEUTRAL GRIP. KEEP BACK STRAIGHT. STICK CHEST OUTWARD AND LOOK AHEAD. \n STEP 2: LIFT DUMBBELLS OFF THE GROUND. AS THE DUMBBELLS PASS YOUR SHIN, JUMP UPWARD. USE THE MOMENTUM TO RAISE DUMBBELLS TO YOUR SHOULDER. STEP 3: AS YOU CATCH THE DUMBBELLS ON THE SHOULDER, SQUAT DOWN WITH THE MOMENTUM. STAND UP STRAIGHT AFTERWARDS. \n STEP 4: BEND KNEES SLIGHTLY AND JUMP \n STEP 5: DURING THE JUMP, RAISE DUMBBELLS OVERHEAD. STAND STRAIGHT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_clean_and_jerk_0.jpg", "dumbbell_clean_and_jerk_1.jpg", "dumbbell_clean_and_jerk_2.jpg"],
        "video": "DUMBBELL_CLEAN_AND_JERK.mp4"
    },
    {
        "id": 49,
        "name": "ABDOMINAL LEG RAISE 2",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE ON THE FLOOR WITH LEGS EXTENDED STRAIGHT, AND HOLD ON TO THE TOP OF THE FLOOR. \n STEP 2: RAISE YOUR LEGS STRAIGHT UP, SLIGHTLY LIFTING YOUR LOWER BACK OFF THE FLOOR. \n STEP 3: HOLD FOR A FEE SECONDS, THEN LOWER YOUR LEGS BACK DOWN TO THE START POSITION. KEEP YOUR LEGS STRAIGHT THROUGHOUT THE MOTION.",
        "images": ["abdominal_leg_raise_2_0.jpg", "abdominal_leg_raise_2_1.jpg", "abdominal_leg_raise_2_2.jpg"],
        "video": "ABDOMINAL_LEG_RAISE_2.mp4"
    },
    {
        "id": 50,
        "name": "BODYWEIGHT SIDE BRIDGE",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LIE ON YOUR SIDE. MAKE SURE ONE LEG IS ON TOP OF THE OTHER. POSITION THE FOREARM ON THE FLOOR PERPENDICULAR WITH YOUR BODY. \n STEP 2: USE YOUR FOREARM TO LIFT YOUR UPPER BODY OF THE GROUND. THE OTHER ARM IS PLACED ON THE SIDE OF YOUR BODY. YOUR BODY SHOULD BE STRAIGHT. ONLY YOUR FOREARM AND THE SIDE OF YOUR FOOT SHOULD BE TOUCHING THE FLOOR. HOLD THIS POSITION.",
        "images": ["bodyweight_side_bridge_0.jpg", "bodyweight_side_bridge_1.jpg"],
        "video": "BODYWEIGHT_SIDE_BRIDGE.mp4"
    },
    {
        "id": 51,
        "name": "BODYWEIGHT SIDE BRIDGE SECOND SIDE",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LIE ON YOUR SIDE. MAKE SURE ONE LEG IS ON TOP OF THE OTHER. POSITION THE FOREARM ON THE FLOOR PERPENDICULAR WITH YOUR BODY. \n STEP 2: USE YOUR FOREARM TO LIFT YOUR UPPER BODY OF THE GROUND. THE OTHER ARM IS PLACED ON THE SIDE OF YOUR BODY. YOUR BODY SHOULD BE STRAIGHT. ONLY YOUR FOREARM AND THE SIDE OF YOUR FOOT SHOULD BE TOUCHING THE FLOOR. HOLD THIS POSITION.",
        "images": ["bodyweight_side_bridge_right_1.jpg"],
        "video": "BODYWEIGHT_SIDE_BRIDGE_right.mp4"
    },
    {
        "id": 52,
        "name": "CHEER PLANK",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: POSITION LEGS ON CHEER. WHILE KEEPING BACK STRAIGHT, PLACE FOREARMS ON THE FLOOR. YOUR FOREARMS ARE PERPENDICULAR WITH YOUR UPPER ARMS. HOLD FOR AS LONG AS YOU CAN.",
        "images": ["cheer_plank_0.jpg"],
        "video": "CHEER_PLANK.mp4"
    },
    {
        "id": 53,
        "name": "BODYWEIGHT LEG RAISE",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: SIT ON THE SIDE OF THE BENCH. HOLD ONTO THE SIDE OF THE BENCH WITH BOTH HANDS AT SHOULDER WIDTH. LIE BACK AND RAISE YOUR LEGS UNTIL YOU REACH A POSITION OF BALANCE. \n STEP 2: BEND YOUR KNEES TOWARDS YOUR UPPER BODY. AT THE SAME TIME, MOVE UPPER BODY FORWARD TO MAINTAIN POSITION OF BALANCE. HOLD FOR NONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_leg_raise_0.jpg", "bodyweight_leg_raise_1.jpg"],
        "video": "BODYWEIGHT_LEG_RAISE.mp4"
    },
    {
        "id": 54,
        "name": "STEAM ENGINE",
        "description": "MUSCLE GROUP:RECTUS ABDOMINIS \n STEP 1. STANDING SO THAT YOUR FEET ARE SHOULDER-WIDTH APART, PLACE YOUR FINGERS BEHIND YOUR EARS\n STEP 2. TOUCH YOUR LEFT ELBOW TO YOUR RIGHT KNEE AS YOU RAISE THE KNEE WHILE YOU REACHING YOUR LEFT POINT TOWARD YOUR RIGHT HIP.\n STEP 3. RETURN TO STARTING POSITION AND REPEAT WITH THE OTHER SIDE. REPEAT THE TWO SEQUENCES REPEATEDLY.",
        "images": ["steam_engine_0.jpg", "steam_engine_1.jpg"],
        "video": "STEAM_ENGINE.mp4"
    },
    {
        "id": 55,
        "name": "BODYWEIGHT SCISSOR KICK",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. PLACE HANDS NEXT TO YOUR SIDES. EXTEND LEGS FULLY AND SLIGHTLY ELEVATED. WHILE KEEPING LEGS STRAIGHT, RAISE ONE LEG UP \n STEP 2: AS YOU LOWER LEG, RAISE THE OTHER LEG UP THIS IS ONE REPETITION.",
        "images": ["bodyweight_scissor_kick_0.jpg", "bodyweight_scissor_kick_1.jpg", "bodyweight_scissor_kick_2.jpg"],
        "video": "BODYWEIGHT_SCISSOR_KICK.mp4"
    },
    {
        "id": 56,
        "name": "WEIGHTED CRUNCH",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. FEET ARE FLAT ON THE FLOOR AND KNEES ARE BENT. FULLY EXTEND YOUR ARMS KEEPING THE WEIGHTED. \n STEP 2: RAISE YOUR UPPER BODY UPWARD WHILE KEEPING YOUR LOWER BACK ON THE FLOOR. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["weighted_crunch_0.jpg", "weighted_crunch_1.jpg"],
        "video": "WEIGHTED_CRUNCH.mp4"
    },
    {
        "id": 57,
        "name": "ONE LEG DROP",
        "description": "MUSCLE GROUSZECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR WITH YOUR HANDS ASIDE, AND YOUR FEET STRAIGHT. \n STEP 2: LIFT ONE LEG, BEND IT TO 90 DEGREES AND LAY IT OVER THE OTHER ONE, THAT STAYS STRAIGHT. \n STEP 3: MAINTAINING THIS POSITION START THE EXERCISE BY LIFTING THE STRAIGHT LEG UP. \n STEP 4: REPEAT THIS POSITION AS NECESSARY. SWITCH LEGS AND REPEAT.",
        "images": ["one_leg_drop_0.jpg", "one_leg_drop_1.jpg"],
        "video": "ONE_LEG_DROP.mp4"
    },
    {
        "id": 58,
        "name": "ONE LEG DROP SECOND SIDE",
        "description": "MUSCLE GROUSZECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR WITH YOUR HANDS ASIDE, AND YOUR FEET STRAIGHT. \n STEP 2: LIFT ONE LEG, BEND IT TO 90 DEGREES AND LAY IT OVER THE OTHER ONE, THAT STAYS STRAIGHT. \n STEP 3: MAINTAINING THIS POSITION START THE EXERCISE BY LIFTING THE STRAIGHT LEG UP. \n STEP 4: REPEAT THIS POSITION AS NECESSARY. SWITCH LEGS AND REPEAT.",
        "images": ["one_leg_drop_right_0.jpg", "one_leg_drop_right_1.jpg"],
        "video": "ONE_LEG_DROP_right.mp4"
    },
    {
        "id": 59,
        "name": "BODYWEIGHT SIDE BRIDGE-1",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: POSITION ONE FOREARM ON THE BENCH WITH YOUR FEET ON THE FLOOR. THE ENTIRE FOREARM SHOULD BE ON THE BENCH. MAKE SURE ONE LEG IS ON TOP OF THE OTHER. THE OTHER ARM IS PLACED ON THE SIDE OF YOUR BODY. \n STEP 2: KEEP YOUR BODY STRAIGHT. ONLY YOUR FOREARM SHOULD BE TOUCHING THE BENCH AND ONLY THE SIDE OF YOUR FOOT SHOULD BE TOUCHING THE FLOOR. HOLD THIS POSITION.",
        "images": ["bodyweight_side_bridge_1_0.jpg", "bodyweight_side_bridge_1_1.jpg"],
        "video": "BODYWEIGHT_SIDE_BRIDGE_1.mp4"
    },
    {
        "id": 60,
        "name": "BODYWEIGHT SIDE BRIDGE-1 SECOND SIDE",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: POSITION ONE FOREARM ON THE BENCH WITH YOUR FEET ON THE FLOOR. THE ENTIRE FOREARM SHOULD BE ON THE BENCH. MAKE SURE ONE LEG IS ON TOP OF THE OTHER. THE OTHER ARM IS PLACED ON THE SIDE OF YOUR BODY. \n STEP 2: KEEP YOUR BODY STRAIGHT. ONLY YOUR FOREARM SHOULD BE TOUCHING THE BENCH AND ONLY THE SIDE OF YOUR FOOT SHOULD BE TOUCHING THE FLOOR. HOLD THIS POSITION.",
        "images": ["bodyweight_side_bridge_right_1_0.jpg", "bodyweight_side_bridge_right_1_1.jpg"],
        "video": "BODYWEIGHT_SIDE_BRIDGE-1_right.mp4"
    },
    {
        "id": 61,
        "name": "BODYWEIGHT SKI JUMP",
        "description": "MUSCLE GROUP:QUADRICEPS \n STEP 1: STAND WITH BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDE. HOP TO THE RIGHT SIDE. AT THE SAME AND BRING YOUR LEFT LEG BEHIND THE RIGHT. FRONT KNEE IS SLIGHTLY BENT. \n STEP 2: HOP TO THE LEFT SIDE. AT THE SAME TIME, LOWER YOUR BODY AND BRING YOUR RIGHT LEG BEHIND THE OTHER. FRONT KNEE IS SLIGHTLY BENT",
        "images": ["bodyweight_ski_jump_0.jpg", "bodyweight_ski_jump_1.jpg"],
        "video": "BODYWEIGHT_SKI_JUMP.mp4"
    },
    {
        "id": 62,
        "name": "DUMBBELL SINGLE LEG DEADLIFT",
        "description": "MUSCLE GROUP: GLUTES \n STEP 1. STAND HOLDING DUMBBELLS IN FRONT OF YOUR THIGHS, PALMS TURNED TOWARD YOUR BODY. YOUR FEET SHOULD BE SHOULDER-WIDTH APART, TOES POINTED FORWARD. \n STEP 2. LIFT YOUR RIGHT FOOT UP BEHIND YOU, A FEW INCHES OFF THE FLOOR, WITH YOUR RIGHT THIGH PERPENDICULAR TO THE FLOOR. PUSH YOUR HIPS BACK AND ALLOW YOUR TORSO TO BEND FORWARD, WHILE KEEPING YOUR ABS TIGHT AND BACK FLAT. YOUR LEFT KNEE SHOULD BENT SIGHTLY. \n STEP 3. BEND FORWARD AS FAR AS YOU CAN WHILE KEEPING YOUR LOWER BACK FLAT. RETURN TO THE STARTING POSITION. REPEAT WITH THE OTHER LEG.",
        "images": ["dumbbell_single_leg_deadlift_1.jpg"],
        "video": "DUMBBELL_SINGLE_LEG_DEADLIFT.mp4"
    },
    {
        "id": 63,
        "name": "DUMBBELL SINGLE LEG DEADLIFT SECOND SIDE",
        "description": "MUSCLE GROUP: GLUTES \n STEP 1. STAND HOLDING DUMBBELLS IN FRONT OF YOUR THIGHS, PALMS TURNED TOWARD YOUR BODY. YOUR FEET SHOULD BE SHOULDER-WIDTH APART, TOES POINTED FORWARD. \n STEP 2. LIFT YOUR RIGHT FOOT UP BEHIND YOU, A FEW INCHES OFF THE FLOOR, WITH YOUR RIGHT THIGH PERPENDICULAR TO THE FLOOR. PUSH YOUR HIPS BACK AND ALLOW YOUR TORSO TO BEND FORWARD, WHILE KEEPING YOUR ABS TIGHT AND BACK FLAT. YOUR LEFT KNEE SHOULD BENT SIGHTLY. \n STEP 3. BEND FORWARD AS FAR AS YOU CAN WHILE KEEPING YOUR LOWER BACK FLAT. RETURN TO THE STARTING POSITION. REPEAT WITH THE OTHER LEG.",
        "images": ["dumbbell_single_leg_deadlift_right_1.jpg"],
        "video": "DUMBBELL_SINGLE_LEG_DEADLIFT_right.mp4"
    },
    {
        "id": 64,
        "name": "LYING HIP EXTENSION",
        "description": "MUSCLE GROUP: GLUTES \n STEP 1. LIE FLAT ON THE FLOOR OR MAT WITH ARLÉ LEG EXTENDED STRAIGHT AND THE OTHER LEG BENT WITH THE FOOT FLAT ON THE FLOOR. PLACE YOUR ARMS DOWN ON THE MAT, ON THE SIDE OF YOUR HIPS. \n STEP 2. RAISE YOUR LOWER BACK OFF THE FLOOR WHILE KEEPING YOUR EXTENDED LEG STRAIGHT. AORD THEN RETURN TO YOUR ORIGINAL POSITION AFTER A FEW REPETITIONS, SWITCH LEGS AND REPEAT WITH THE OTHER SIDE.",
        "images": ["lying_hip_extension_0.jpg", "lying_hip_extension_1.jpg", "lying_hip_extension_2.jpg"],
        "video": "LYING_HIP_EXTENSION.mp4"
    },
    {
        "id": 65,
        "name": "BODYWEIGHT ARM AND LEG LIFT STRAIGHT",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: KEEP YOUR LEGS DOWN AND PLACE YOUR HANDS ON THE FLOOR. RAISE YOUR RIGHT ARM AND LEFT LEG UP INTO THE AIR. \n STEP 2: BRING YOUR ARM AND LEG OUTWARD. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_arm_and_leg_lift_straight_0.jpg"],
        "video": "BODYWEIGHT_ARM_AND_LEG_LIFT_STRAIGHT.mp4"
    },
    {
        "id": 66,
        "name": "LYING HIP EXTENSION 1",
        "description": "MUSCLE GROUP: GLUTES \n STEP 1. LIE FLAT ON THE FLOOR OR MAT WITH ARLÉ LEG EXTENDED STRAIGHT AND THE OTHER LEG BENT WITH THE FOOT FLAT ON THE FLOOR. PLACE YOUR ARMS DOWN ON THE MAT, ON THE SIDE OF YOUR HIPS. \n STEP 2. RAISE YOUR LOWER BACK OFF THE FLOOR WHILE KEEPING YOUR EXTENDED LEG STRAIGHT. HOLD THEN RETURN TO YOUR ORIGINAL POSITION AFTER A FEW REPETITIONS, SWITCH LEGS AND REPEAT WITH THE OTHER SIDE.",
        "images": ["lying_hip_extension_1_0.jpg", "lying_hip_extension_1_1.jpg"],
        "video": "LYING_HIP_EXTENSION_1.mp4"
    },
    {
        "id": 67,
        "name": "BODYWEIGHT ARM AND LEG LIFT STRAIGHT SECOND SIDE",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: KEEP YOUR LEGS DOWN AND PLACE YOUR HANDS ON THE FLOOR. RAISE YOUR RIGHT ARM AND LEFT LEG UP INTO THE AIR. \n STEP 2: BRING YOUR ARM AND LEG OUTWARD. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_arm_and_leg_lift_straight_1.jpg"],
        "video": "BODYWEIGHT_ARM_AND_LEG_LIFT_STRAIGHT_right.mp4"
    },
    {
        "id": 68,
        "name": "LYING HIP EXTENSION 1 SECOND SIDE",
        "description": "MUSCLE GROUP: GLUTES \n STEP 1. LIE FLAT ON THE FLOOR OR MAT WITH ARLÉ LEG EXTENDED STRAIGHT AND THE OTHER LEG BENT WITH THE FOOT FLAT ON THE FLOOR. PLACE YOUR ARMS DOWN ON THE MAT, ON THE SIDE OF YOUR HIPS. \n STEP 2. RAISE YOUR LOWER BACK OFF THE FLOOR WHILE KEEPING YOUR EXTENDED LEG STRAIGHT. HOLD THEN RETURN TO YOUR ORIGINAL POSITION AFTER A FEW REPETITIONS, SWITCH LEGS AND REPEAT WITH THE OTHER SIDE.",
        "images": ["lying_hip_extension_1_right_0.jpg", "lying_hip_extension_1_right_1.jpg"],
        "video": "LYING_HIP_EXTENSION-1_right.mp4"
    },
    {
        "id": 69,
        "name": "MEDICINE BALL CRUNCH",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. HOLD MEDICINE BALL OVERHEAD WITH ARMS FULLY EXTENDED. KEEP KNEES BENT AND FEET FLAT ON FLOOR. \n STEP 2: RAISE YOUR UPPER BODY UPWARD WHILE KEEPING YOUR LOWER BACK ON THE FLOOR. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["medicine_ball_crunch_0.jpg", "medicine_ball_crunch_1.jpg"],
        "video": "MEDICINE_BALL_CRUNCH.mp4"
    },
    {
        "id": 70,
        "name": "DUMBBELL ROTATING T EXTENSION",
        "description": "MUSCLE NAME: QUADRICEPS \n STEP 1. START IN A PUSHUP POSITION. KEEPING YOUR ARMS STRAIGHT AND YOUR CORE ENGAGED \n STEP 2. SHIFT YOUR WEIGHT ONTO YOUR LEFT ARM, ROTATE YOUR TORSO TO THE RIGHT, AND RAISE YOUR RIGHT ARM TOWARD THE CEILING SO THAT YOUR BODY FORMS A T. \n STEP 3. HOLD FOR THREE SECONDS, THEN RETURN TO START AND REPEAT ON THE OTHER SIDE. THAT'S ONE REP.",
        "images": ["dumbbell_rotating_t_extension_0.jpg", "dumbbell_rotating_t_extension_1.jpg"],
        "video": "DUMBBELL_ROTATING_T_EXTENSION.mp4"
    },
    {
        "id": 71,
        "name": "DUMBBELL ROTATING T EXTENSION SECOND SIDE",
        "description": "MUSCLE NAME: QUADRICEPS \n STEP 1. START IN A PUSHUP POSITION. KEEPING YOUR ARMS STRAIGHT AND YOUR CORE ENGAGED \n STEP 2. SHIFT YOUR WEIGHT ONTO YOUR LEFT ARM, ROTATE YOUR TORSO TO THE RIGHT, AND RAISE YOUR RIGHT ARM TOWARD THE CEILING SO THAT YOUR BODY FORMS A T. \n STEP 3. HOLD FOR THREE SECONDS, THEN RETURN TO START AND REPEAT ON THE OTHER SIDE. THAT'S ONE REP.",
        "images": ["dumbbell_rotating_t_extension_right_0.jpg", "dumbbell_rotating_t_extension_right_1.jpg"],
        "video": "DUMBBELL_ROTATING_T_EXTENSION_right.mp4"
    },
    {
        "id": 72,
        "name": "BODYWEIGHT TOE TOUCH 3",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. LIFT LEGS UNTIL LEGS ARE PERPENDICULAR WITH THE FLOOR. FULLY EXTEND YOUR ARMS ABOVE YOU. \n STEP 2: REACH FOR YOUR TOES WITH YOUR HANDS. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_toe_touch_3_0.jpg", "bodyweight_toe_touch_3_1.jpg"],
        "video": "BODYWEIGHT_TOE_TOUCH_3.mp4"
    },
    {
        "id": 73,
        "name": "BODYWEIGHT TRUNK ROTATION",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LIE DOWN ON THE FLOOR. LIFT LEGS UNTIL THIGHS ARE PERPENDICULAR WITH THE GROUND. BEND YOUR KNEES. FULLY EXTEND YOUR ARMS TO YOUR SIDES. \n STEP 2: WHILE TWISTING THE UPPER BODY, LOWER YOUR LEGS TO ONE SIDE. HOLD FOR ONE SECOND. \n STEP 3: RETURN TO STARTING POSITION \n STEP 4: WHILE TWISTING THE UPPER BODY, LOWER YOUR TO THE OTHER SIDE. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_trunk_rotation_0.jpg", "bodyweight_trunk_rotation_1.jpg", "bodyweight_trunk_rotation_2.jpg"],
        "video": "BODYWEIGHT_TRUNK_ROTATION.mp4"
    },
    {
        "id": 74,
        "name": "DUMBBELL SINGLE ARM",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELL WITH OVERHAND GRIP. POSITION THE DUMBBELL NEXT TO YOUR HEAD. \n STEP 2: BEND KNEES SLIGHTLY. \n STEP 3: JUMP AND PUSH THE DUMBBELL UP. RAISE DUMBBELL OVERHEAD WITH ARMS FULLY EXTENDED. LAND WITH ONE FOOT FORWARD AND ONE FOOT BEHIND. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_single_arm_0.jpg", "dumbbell_single_arm_1.jpg"],
        "video": "DUMBBELL_SINGLE_ARM.mp4"
    },
    {
        "id": 75,
        "name": "DUMBBELL SINGLE ARM SECOND SIDE",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELL WITH OVERHAND GRIP. POSITION THE DUMBBELL NEXT TO YOUR HEAD. \n STEP 2: BEND KNEES SLIGHTLY. \n STEP 3: JUMP AND PUSH THE DUMBBELL UP. RAISE DUMBBELL OVERHEAD WITH ARMS FULLY EXTENDED. LAND WITH ONE FOOT FORWARD AND ONE FOOT BEHIND. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_single_arm_right_0.jpg", "dumbbell_single_arm_right_1.jpg"],
        "video": "DUMBBELL_SINGLE_ARM_right.mp4"
    },
    {
        "id": 76,
        "name": "BODYWEIGHT PUSH-UP DRIVE BUMPER",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS NEXT TO YOUR LOWER CHEST. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. LIFT YOUR BEHIND UP IN THE AIR. ARMS SHOULD STRAIGHTEN OUT. \n STEP 2: PRETENDING THAT THERE IS AN IMAGINARY BAR TWO FEET FROM THE GROUND, GO UNDER THE BAR UNTIL YOUR ENTIRE UPPER BODY PASSED THE BAR. THE ELBOWS SHOULD BEND. ARMS STRAIGHTEN OUT AT THE END OF THE MOVEMENT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_push_up_drive_bumper_0.jpg", "bodyweight_push_up_drive_bumper_1.jpg"],
        "video": "BODYWEIGHT_PUSH-UP_DRIVE_BUMPER.mp4"
    },
    {
        "id": 77,
        "name": "DUMBBELL PUSH UP PRESS",
        "description": "MUSCLE GROUP: GLUTES, QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELLS WITH NEUTRAL GRIP. DUMBBELLS ARE POSITIONED ON YOUR SHOULDERS. \n STEP 2: BEND KNEES SLIGHTLY. \n STEP 3: PUSH UP UNTIL YOUR ARMS ARE FULLY EXTENDED OVERHEAD. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_push_up_press_0.jpg", "dumbbell_push_up_press_1.jpg"],
        "video": "DUMBBELL_PUSH_UP_PRESS.mp4"
    },
    {
        "id": 78,
        "name": "BENCH KNEE UP",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND TALL WITH YOUR BACK STRAIGHT. KEEP YOUR HANDS AT YOUR SIDES. \n STEP 2: BEND KNEES SLIGHTLY. MOVE FROM TO THE SIDES SUPPORTING YOUR LEG ON THE BENCH. \n STEP 3: JUMP UP AS HIGH AS YOU CAN. BRING YOUR KNEES TOWARD YOUR CHEST.",
        "images": ["bench_knee_up_0.jpg", "bench_knee_up_1.jpg", "bench_knee_up_2.jpg", "bench_knee_up_3.jpg", "bench_knee_up_4.jpg", "bench_knee_up_5.jpg"],
        "video": "BENCH_KNEE_UP.mp4"
    },
    {
        "id": 79,
        "name": "BODYWEIGHT PUSH-UP REGULAR",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. POSITION HANDS UNDER YOUR SHOULDERS. DISTANCE BETWEEN YOUR HANDS SHOULD BE NARROWER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_push_up_regular_0.jpg", "bodyweight_push_up_regular_1.jpg"],
        "video": "BODYWEIGHT_PUSH-UP_REGULAR.mp4"
    },
    {
        "id": 80,
        "name": "CHAIR BENT KNEES",
        "description": "MUSCLE GROUP: TRICEPS BRACHII \n STEP 1: PLACE YOUR PALMS AT THE EDGE OF THE BENCH WITH FINGERS CURLED AROUND THE EDGE OF THE CHAIR. KEEP YOUR ARMS WIDER THAN SHOULDER WIDTH APART. POSITION THE REST OF YOUR BODY IN A SITTING POSITION IN FRONT OF THE CHAIR. KEEP KNEES BENT. \n STEP 2: BEND YOUR ARMS UNTIL YOUR UPPER ARMS ARE NEARLY PARALLEL WITH THE GROUND. HOLD FOR A SECOND. RETURN TO STARTING POSITION.",
        "images": ["chair_bent_knees_0.jpg", "chair_bent_knees_1.jpg"],
        "video": "CHAIR_BENT_KNEES.mp4"
    },
    {
        "id": 81,
        "name": "BODYWEIGHT SUPERMAN",
        "description": "MUSCLE GROUP: LOWER BACK \n STEP 1: LIE PRONE ON THE FLOOR. FULLY EXTEND YOUR ARMS IN FRONT OF YOU. \n STEP 2: RAISE YOUR LEGS AND UPPER BODY TOWARDS THE CEILING. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_superman_0.jpg", "bodyweight_superman_1.jpg"],
        "video": "BODYWEIGHT_SUPERMAN.mp4"
    },
    {
        "id": 82,
        "name": "BODYWEIGHT PLANK LEG TOUCH",
        "description": "MUSCLE GROUP: LOWER BACK \n STEP 1: LIE PRONE ON THE FLOOR. RAISE YOURSELF UP SO THAT ONLY YOUR TOES AND FOREARMS ARE ON THE FLOOR. KEEP YOUR BACK STRAIGHT. LIFT YOUR RIGHT LEG UP. TOUCH YOUR HEEL. RETURN TO THE PLANK POSITION.",
        "images": ["bodyweight_plank_leg_touch_0.jpg", "bodyweight_plank_leg_touch_1.jpg", "bodyweight_plank_leg_touch_2.jpg", "bodyweight_plank_leg_touch_3.jpg"],
        "video": "BODYWEIGHT_PLANK_LEG_TOUCH.mp4"
    },
    {
        "id": 83,
        "name": "BARBELL ROW",
        "description": "MUSCLE GROUP: LATISSIMUS DORSI \n STEP 1: BEND YOUR KNEES SLIGHTLY. KEEP BACK BENT AND STRAIGHT. HOLD BARBELL UNDER YOU WITH SHOULDER WIDTH UNDERHAND GRIP. \n STEP 2: RAISE THE BARBELL VERTICALLY TOWARDS YOUR CHEST. REFRAIN FROM FLARING YOUR ELBOWS OUT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["barbell_row_0.jpg", "barbell_row_1.jpg"],
        "video": "BARBELL_ROW.mp4"
    },
    {
        "id": 84,
        "name": "EZ CURL BAR BICEPS CURL",
        "description": "MUSCLE GROUP: BICEPS BRACHII \n STEP 1: WHILE STANDING WITH BACK STRAIGHT, HOLD EZ CURL BAR WITH SHOULDER WIDTH UNDERHAND GRIP. EZ CURL BAR IS POSITIONED IN FRONT OF YOUR THIGHS. \n STEP 2: LIFT EZ CURL BAR UP WHILE KEEPING YOUR UPPER ARMS IN PLACE REFRAIN FROM USING YOUR SHOULDERS DURING THE MOVEMENT. HOLD FOR ONE SECOND. LOWER YOUR ARMS BACK TO STARTING POSITION.",
        "images": ["ez_curl_bar_biceps_curl_0.jpg", "ez_curl_bar_biceps_curl_1.jpg"],
        "video": "EZ_CURL_BAR_BICEPS_CURL.mp4"
    },
    {
        "id": 85,
        "name": "BAR BENCH PRESS INCLINE",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE BACK ON THE INCLINE BENCH. HOLD THE EZ CURL BAR WITH OVERHAND GRIP. DISTANCE BETWEEN YOUR HANDS IS SLIGHTER WIDER THAN SHOULDER WIDTH. HOLD THE EZ CURL BAR WITH ARMS FULLY EXTENDED. THE EZ CURL BAR IS DIRECTLY ABOVE THE CENTER OF YOUR CHEST. \n STEP 2: LOWER THE EZ CURL BAR TOWARDS YOUR LOWER CHEST AS YOU KEEP YOUR ELBOWS CLOSE TO YOUR BODY. THE EZ CURL BAR SHOULD SLIGHTLY TOUCH YOUR CHEST AT THE END OF THE MOVEMENT. REFRAIN FROM BOUNCING THE EZ CURL BAR OFF YOUR CHEST. HOLD FOR A BRIEF MOMENT. RETURN STARTING POSITION. KEEP YOUR ENTIRE BACK ON THE BENCH AT ALL TIMES. REFRAIN FROM ANY LEG MOVEMENTS.",
        "images": ["bar_bench_press_incline_0.jpg", "bar_bench_press_incline_1.jpg"],
        "video": "BAR_BENCH_PRESS_INCLINE.mp4"
    },
    {
        "id": 86,
        "name": "DUMBBELL DECLINE FLY",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE DOWN ON THE DECLINE BENCH. HOLD ONTO TWO DUMBBELLS WITH NEUTRAL GRIP. FULLY EXTEND YOUR ARMS ABOVE YOUR CHEST. \n STEP 2: WHILE MAINTAINING A SLIGHT BEND IN YOUR ELBOWS, LOWER DUMBBELLS TO EACH SIDE UNTIL THE DUMBBELLS ARE NEXT TO YOUR UPPER BODY. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_decline_fly_0.jpg", "dumbbell_decline_fly_1.jpg"],
        "video": "DUMBBELL_DECLINE_FLY.mp4"
    },
    {
        "id": 87,
        "name": "DUMBBELL FLY INCLINE BENCH",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE DOWN ON THE INCLINE BENCH. HOLD ONTO TWO DUMBBELLS WITH NEUTRAL GRIP. FULLY EXTEND YOUR ARMS ABOVE YOUR CHEST. \n STEP 2: WHILE MAINTAINING A SLIGHT BEND IN YOUR ELBOWS, LOWER DUMBBELLS TO EACH SIDE UNTIL THE DUMBBELLS ARE NEXT TO YOUR UPPER BODY. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_fly_incline_bench_0.jpg", "dumbbell_fly_incline_bench_1.jpg"],
        "video": "DUMBBELL_FLY_INCLINE_BENCH.mp4"
    },
    {
        "id": 88,
        "name": "BENCH DECLINE PUSH-UP",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1. PLACE YOUR FEET ON A BENCH OR ANY ELEVATED STEP AND GET INTO A STANDARD PUSHUP POSITION. \n STEP 2. LOWER YOUR BODY UNTIL YOUR CHEST NEARLY TOUCHES THE FLOOR, PAUSE, THEN PUSH YOURSELF BACK TO THE STARTING POSITION. MAINTAIN PROPER FORM THROUGHOUT BY PREVENTING YOUR HIPS FROM SAGGING AT ANY POINT, KEEP YOUR CORE STIFF BY BRACING YOUR ABDOMINAL MUSCLES AND STRAIGHTEN YOUR LEGS WHILE PLACING YOUR WEIGHT ON YOUR TOES.",
        "images": ["bench_decline_push_up_0.jpg", "bench_decline_push_up_1.jpg"],
        "video": "BENCH_DECLINE_PUSH-UP.mp4"
    },
    {
        "id": 89,
        "name": "DUMBBELL ROW KICKBACK",
        "description": "MUSCLE GROUP: LOWER BACK \n STEP 1. STAND WITH YOUR FEET SHOULDER- WIDTH APART AND WITH YOUR KNEES SLIGHTLY BENT. HOLD A LIGHT DUMBBELL IN EACH HAND AND BEND FORWARD AT THE WAIST UNTIL YOUR TORSO IS ALMOST PARALLEL TO THE FLOOR. HANG YOUR ARMS STRAIGHT DOWN WITH YOUR FACING IN, AS ILLUSTRATED. \n STEP 2. ROW THE WEIGHTS STRAIGHT UP UNTIL THEY REACH THE SIDES OF YOUR CHEST AND YOUR ARHIS E BENT AT RIGHT ANGLES. IDEALLY, YOUR UPPER ARMS SHOULD BE PARALLEL TO THE FLOOR. \n STEP 4. SQUEEZE YOUR TRICEPS, THEN BEND YOUR ELBOWS TO LOWER THE WEIGHTS BACK DOWN SO THAT THEY ARE ALONG YOUR SIDES ONCE AGAIN. \n STEP 5. FINALLY, LOWER THE WEIGHTS BACK DOWN UNTIL YOUR ARMS ARE HANGING STRAIGHT DOWN.",
        "images": ["dumbbell_row_kickback_0.jpg", "dumbbell_row_kickback_1.jpg", "dumbbell_row_kickback_2.jpg"],
        "video": "DUMBBELL_ROW_KICKBACK.mp4"
    },
    {
        "id": 90,
        "name": "BARBELL SQUAT 2",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. PLACE BARBELL ON THE BACK OF YOUR SHOULDERS. HOLD BARBELL WITH OVERHAND GRIP. DISTANCE BETWEEN YOUR HANDS SHOULD BE WIDER THAN SHOULDER WIDTH APART. ADJUST FEET TO FACE SLIGHTLY OUTWARD \n STEP 2: LOWER YOURSELF BY BENDING YOUR KNEES. YOUR BACK IS STRAIGHT THROUGHOUT THE WHOLE MOVEMENT. STOP WHEN YOUR THIGHS ARE PARALLEL WITH THE GROUND. WHEN YOU RETURN THE STARTING POSITION, GENERATE ENERGY FROM YOUR LOWER BACK.",
        "images": ["barbell_squat_2_0.jpg", "barbell_squat_2_1.jpg"],
        "video": "BARBELL_SQUAT_2.mp4"
    },
    {
        "id": 91,
        "name": "BARBELL CALF RAISE",
        "description": "MUSCLE GROUP: GASTROCNEMIUS \n STEP 1: WHILE STANDING WITH BACK STRAIGHT, POSITION BARBELL ON TOP OF YOUR SHOULDERS. HOLD BARBELL WITH OVERHAND GRIP. DISTANCE BETWEEN HANDS SHOULD BE WIDER THAN SHOULDER WIDTH APART. \n STEP 2: RAISE YOUR CALVES BY TIPTOEING. HOLD FOR ONE SECOND. LOWER YOUR CALVES BACK TO THE GROUND.",
        "images": ["barbell_calf_raise_0.jpg", "barbell_calf_raise_1.jpg"],
        "video": "BARBELL_CALF_RAISE.mp4"
    },
    {
        "id": 92,
        "name": "STANDING SCARECROW 2",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1. STAND UPRIGHT AND HOLD A LIGHT DUMBBELL ON EITHER SIDE OF YOUR LOWER CHEST, WITH FOREARMS POINTING STRAIGHT DOWN AND UPPER ARMS OUT TO THE SIDES YET SLIGHTLY LOWER THAN PARALLEL TO THE FLOOR. \n STEP 2. KEEP YOUR SHOULDERS RELAXED SHRUG YOUR SHOULDERS AS IF YOU WERE TRYING FOLTOECH THEM TO YOUR EARS \n STEP 3. HOLD THE TOP MOST POSITION, THEN GRADUALLY LOWER THEM TO THE STARTING POSITION. DO NOT BEND YOUR ELBOWS OR SHIFT YOUR HEAD FORWARD DURING THE MOTION REPEAT.",
        "images": ["standing_scarecrow_2_0.jpg", "standing_scarecrow_2_1.jpg", "standing_scarecrow_2_2.jpg"],
        "video": "STANDING_SCARECROW_2.mp4"
    },
    {
        "id": 93,
        "name": "DUMBBELL SHOULDER PRESS",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1: WHILE SEATED WITH BACK STRAIGHT, HOLD DUMBBELLS WITH OVERHAND GRIP. POSITION DUMBBELLS NEXT TO THE SIDES OF YOUR HEAD. \n STEP 2: LIFT DUMBBELLS OVERHEAD UNTIL YOUR ARMS ARE FULLY EXTENDED. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_shoulder_press_0.jpg", "dumbbell_shoulder_press_1.jpg", "dumbbell_shoulder_press_2.jpg"],
        "video": "DUMBBELL_SHOULDER_PRESS.mp4"
    },
    {
        "id": 94,
        "name": "DUMBBELL REAR DELT ROW",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1. BEND OVER AT THE WAIST HOLDING THE DUMBBELL WITH YOUR ARMS STRAIGHT AND PALMS FACING IN, YOUR FEET HIP-WIDTH APART. \n STEP 2. RAISE THE DUMBBELL UP AND OUTWARD TO SHOULDER HEIGHT, KEEPING YOUR BACK FLAT. BEND YOUR ELBOWS SLIGHTLY AS YOU LIFT IF NECESSARY, THEN LOWER THE DUMBBELL BACK TO THE START POSITION.",
        "images": ["dumbbell_rear_delt_row_0.jpg", "dumbbell_rear_delt_row_1.jpg"],
        "video": "DUMBBELL_REAR_DELT_ROW.mp4"
    },
    {
        "id": 95,
        "name": "FRONT PLATE RAISE",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1. STAND UPRIGHT, GRAB A SINGLE WEIGHT PLATE WITH ONE HAND ON EACH SIDE OF THE PLATE SIMILAR TO A CAR STEERING WHEEL. \n STEP 2. RAISE THE IN FRONT OF YOU UNTIL YOU CAN SEE DOWN THE CENTER. \n STEP 3. PAUSE FOR A FEW SECONDS, THEN LOWER IT IN A CONTROLLED AND SLOW MOTION.",
        "images": ["front_plate_raise_2.jpg", "front_plate_raise_3.jpg"],
        "video": "FRONT_PLATE_RAISE.mp4"
    },
    {
        "id": 96,
        "name": "BAR UPRIGHT ROW",
        "description": "MUSCLE GROUP: DELTOIDS \n STEP 1. STAND WITH YOUR FEET SLIGHTLY WIDER THAN FA SHOULDER-WIDTH APART AND TAKE AN OVERHAND GRIP ON A BARBELL WITH YOUR HANDS ALSO A SHOULDER-WIDTH APART. \n STEP 2. PULL UP TO THE LEVEL OF YOUR CHIN, KEEPING THE BAR CLOSE TO YOUR BODY AND KEEPING YOUR ELBOWS HIGHER THAN THE BAR. \n STEP 3. HOLD FOR A FEW SECONDS BEFORE LOWERING BACK TO THE START POSITION, ENSURING THAT YOUR ELBOWS REMAIN SLIGHTLY BENT AND AVDIDIRIG ANY BOUNCING OR JERKING MOVEMENTS.",
        "images": ["bar_upright_row_0.jpg", "bar_upright_row_1.jpg"],
        "video": "BAR_UPRIGHT_ROW.mp4"
    },
    {
        "id": 97,
        "name": "DUMBBELL SHRUG",
        "description": "MUSCLE GROUP: TRAPEZIUS \n STEP 1. STAND UPRIGHT AND HOLD TWO FAIRLY AEAVY DUMBBELLS AT YOUR SIDES, WITH YOUR PALMS FACING EACH OTHER (NEUTRAL-GRIP). \n STEP 2. KEEP YOUR SHOULDERS RELAXED SHRUG YOUR SHOULDERS AS IF YOU WERE TRYING FOLTOTCH THEM TO YOUR EARS. \n STEP 3. HOLD THE TOP MOST POSITION, THEN GRADUALLY LOWER THEM TO THE STARTING POSITION. DO NOT BEND YOUR ELBOWS OR SHIFT HEAD FORWARD DURING THE MOTION. REPEAT.",
        "images": ["dumbbell_shrug_0.jpg", "dumbbell_shrug_1.jpg"],
        "video": "DUMBBELL_SHRUG.mp4"
    },
    {
        "id": 98,
        "name": "BODYWEIGHT TOE TOUCH 1",
        "description": "MUSCLE GRUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. EXTEND YOUR LEGS PUT YOUR HANDS BEHIND YOUR HEAD. \n STEP 2: REACH YOUR TOES WITH YOUR HANDS. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_toe_touch_1_0.jpg", "bodyweight_toe_touch_1_1.jpg", "bodyweight_toe_touch_1_2.jpg"],
        "video": "BODYWEIGHT_TOE_TOUCH_1.mp4"
    },
    {
        "id": 99,
        "name": "BODYWEIGHT TOE TOUCH 2",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE DOWN ON THE FLOOR. LIFT LEGS UNTIL UNTIL LEGS ARE PERPENDICULAR WITH THE FLOOR. FULLY EXTEND YOUR ARMS ABOVE YOU. \n STEP 2: REACH FOR YOUR TOES WITH YOUR HAND. MOVE TO THE SIDE AFTER EVERY TOUCHING AND COME RETURN TO STARTING POSITION AT THE MIDDLE.",
        "images": ["bodyweight_toe_touch_2_0.jpg", "bodyweight_toe_touch_2_1.jpg", "bodyweight_toe_touch_2_2.jpg"],
        "video": "BODYWEIGHT_TOE_TOUCH_2.mp4"
    },
    {
        "id": 100,
        "name": "BODYWEIGHT SIT-UP",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE BACK ON THE FLOOR. PUT HANDS BEHIND YOUR HEAD. KNEES ARE BEND AND FEET ARE ON THE FLOOR. \n STEP 2: RAISE YOUR UPPER BODY UPWARD. HOLD FOR ONE SECOND. RETURN TO YOUR STARTING POSITION.",
        "images": ["bodyweight_sit_up_0.jpg", "bodyweight_sit_up_1.jpg"],
        "video": "BODYWEIGHT_SIT-UP.mp4"
    },
    {
        "id": 101,
        "name": "SWISS BALL CRUNCH",
        "description": "MUSCLE GROUP: RECTUS ABDOMINIS \n STEP 1: LIE BACK ON THE STABILITY BALL. POSITION HANDS ON YOUR HEAD AND FEET ON THE FLOOR. \n STEP 2: RAISE YOUR UPPER BODY UPWARD WHILE KEEPING YOUR LOWER BACK ON THE STABILITY BALL. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["swiss_ball_crunch_0.jpg", "swiss_ball_crunch_1.jpg"],
        "video": "SWISS_BALL_CRUNCH.mp4"
    },
    {
        "id": 102,
        "name": "DUMBBELL LUNGE FORWARD",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELLS OVERHEAD WITH ARMS STRAIGHT. \n STEP 2: WHILE KEEPING YOUR BACK STRAIGHT, STEP FORWARD WITH ONE FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. \n STEP 3: STEP BACK AND RETURN TO STARTING POSITION. \n STEP 4: WHILE KEEPING YOUR BACK STRAIGHT, STEP FORWARD WITH THE OTHER FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD FOR ONE SECOND. STEP BACK AND RETURN TO STARTING POSITION.",
        "images": ["dumbbell_lunge_forward_2.jpg", "dumbbell_lunge_forward_3.jpg"],
        "video": "DUMBBELL_LUNGE_FORWARD.mp4"
    },
    {
        "id": 103,
        "name": "DUMBBELL T-PUSH-UP",
        "description": "MUSCLE GROUP: PECTORIALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR PALMS ON THE FLOOR. HOLD DUMBBELLS WITH NEUTRAL GRIP. POSITION HANDS NEXT TO YOUR LOWER CHEST. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR PALMS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST LIS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. \n STEP 3: RETURN TO STARTING POSITION. \n STEP 4: RAISE ONE ARM UNTIL DUMBBELL POINTS TO THE CEILING. HOLD FOR ONE SECONDS \n STEP 5: RETURN TO STARTING POSITION. \n STEP 6: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. \n STEP 7: RETURN TO STARTING POSITION.",
        "images": ["dumbbell_t_push_up_0.jpg", "dumbbell_t_push_up_1.jpg", "dumbbell_t_push_up_2.jpg"],
        "video": "DUMBBELL_T-PUSH-UP.mp4"
    },
    {
        "id": 104,
        "name": "BODYWEIGHT SCISSOR HORIZONTAL",
        "description": "MUSCLE GROUP: OBLIQUES \n STEP 1: LIE DOWN ON THE FLOOR. PLACE HANDS NEXT TO YOUR SIDES. EXTEND LEGS FULLY AND SLIGHTLY ELEVATED. WHILE, KEEPING LEGS STRAIGHT, RAISE ONE LEG HIGHER THEN THE OTHER. \n STEP 2: EXTEND BOTH LEGS WIDE AND OUTWARD. \n STEP 3: AS YOUR LOWER LEG, RAISE THE OTHER LEG UP. \n STEP 4: EXTEND BOTH LEGS WIDE AND OUTWARD.",
        "images": ["bodyweight_scissor_horizontal_0.jpg", "bodyweight_scissor_horizontal_1.jpg", "bodyweight_scissor_horizontal_2.jpg"],
        "video": "BODYWEIGHT_SCISSOR_HORIZONTAL.mp4"
    },
    {
        "id": 105,
        "name": "MEDICINE BALL SQUAT",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT FEET SHOULDER WIDTH APART. HOLD THE MEDICINE BALL IN FRONT OF YOU. ADJUST FEET TO FACE SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF BY BENDING YOUR KNEES. YOUR BACK SHOULD BE STRAIGHT THROUGHOUT THE WHOLE MOVEMENT. STOP WHEN YOUR THIGHS ARE PARALLEL WITH THE GROUND. WHEN YOU RETURN THE STARTING POSITION, GENERATE ENERGY FROM YOUR LOWER BACK.",
        "images": ["medicine_ball_squat_0.jpg", "medicine_ball_squat_1.jpg"],
        "video": "MEDICINE_BALL_SQUAT.mp4"
    },
    {
        "id": 106,
        "name": "BARBELL SQUAD ASSISTED",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH A FLAT BENCH BEHIND YOU. FEET ARE SHOULDER WIDTH APART. PLACE BARBELL ON THE BACK OF YOUR SHOULDERS. HOLD BARBELL WITH OVERHAND GRIP. DISTANCE BETWEEN YOUR HANDS SHOULD BE WIDER THAN SHOULDER WIDTH APART. ADJUST FEET TO FACE SLIGHTLY OUTWARD. \n STEP 2: LOWER YOURSELF BY BENDING YOUR KNEES. YOUR BACK IS STRAIGHT THROUGHOUT THE WHOLE MOVEMENT. STOP WHEN YOUR THIGHS ARE PARALLEL WITH THE GROUND OR WHEN YOUR BEHIND TOUCHES THE BENCH. WHEN YOU RETURN THE STARTING POSITION, GENERATE ENERGY FROM YOUR LOWER BACK.",
        "images": ["barbell_squad_assisted_0.jpg", "barbell_squad_assisted_1.jpg"],
        "video": "BARBELL_SQUAD_ASSISTED.mp4"
    },
    {
        "id": 107,
        "name": "DUMBBELL BICEPS CURL",
        "description": "MUSCLE GROUP: BRACHIORADIALIS \n STEP 1: WHILE STANDING WITH BACK STRAIGHT, HOLD DUMBBELLS AT YOUR SIDES WITH NEUTRAL GRIP. KEEP ARMS STRAIGHT. \n STEP 2: LIFT DUMBBELLS UP WHILE KEEPING YOUR UPPER ARMS IN PLACE REFRAIN FROM USING YOUR SHOULDERS DURING THE MOVEMENT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_biceps_curl_0.jpg", "dumbbell_biceps_curl_1.jpg"],
        "video": "DUMBBELL_BICEPS_CURL.mp4"
    },
    {
        "id": 108,
        "name": "DUMBBELL BICEPS NECURAL INCLINE",
        "description": "MUSCLE GROUP: BRACHIORADIALIS \n STEP 1: LIE PRONE ON THE INCLINE BENCH. LET DUMBBELLS HANG NEXT TO YOU WITH NEUTRAL GRIP. KEEP ARMS STRAIGHT. \n STEP 2: LIFT DUMBBELLS UP WHILE KEEPING YOUR UPPER ARMS IN PLACE REFRAIN FROM USING YOUR SHOULDERS DURING THE MOVEMENT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_biceps_necural_incline_0.jpg", "dumbbell_biceps_necural_incline_1.jpg"],
        "video": "DUMBBELL_BICEPS_NECURAL_INCLINE.mp4"
    },
    {
        "id": 109,
        "name": "UMBBELL BICEPS CURL BENCH",
        "description": "MUSCLE GROUP: BICEBS BRACHII \n STEP 1: SID DOWN ON THE BENCH. KEEP BACK BENT AND STRAIGHT. HOLD ONE DUMBBELL WITH UNDERHAND GRIP. POSITION ELBOW AT THE INNER THIGH. \n STEP 2: LIFT DUMBBELL UP WHILE KEEPING YOUR UPPER ARM IN PLACE. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_biceps_curl_bench_0.jpg", "dumbbell_biceps_curl_bench_1.jpg"],
        "video": "DUMBBELL_BICEPS_CURL_BENCH.mp4"
    },
    {
        "id": 110,
        "name": "UMBBELL BICEPS CURL BENCH SECOND SIDE",
        "description": "MUSCLE GROUP: BICEBS BRACHII \n STEP 1: SID DOWN ON THE BENCH. KEEP BACK BENT AND STRAIGHT. HOLD ONE DUMBBELL WITH UNDERHAND GRIP. POSITION ELBOW AT THE INNER THIGH. \n STEP 2: LIFT DUMBBELL UP WHILE KEEPING YOUR UPPER ARM IN PLACE. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_biceps_curl_bench_right_0.jpg", "dumbbell_biceps_curl_bench_right_1.jpg"],
        "video": "DUMBBELL_BICEPS_CURL_BENCH_right.mp4"
    },
    {
        "id": 111,
        "name": "STANDING TRICEPS EXTENSION",
        "description": "MUSCLE GROUP: TRICEPS BRACHII \n STEP 1. STAND STRAIGHT UPRIGHT WITH YOUR FEET SHOULDER-WIDTH APART, HOLDING A DUMBBELL OVERHEAD WITH BOTH HANDS UNDER THE INNER PLATE, AS SHOWN. HAVE IT HANG BEHIND YOUR UPPER BACK WITH ELBOWS BENT. \n STEP 2. RAISE THE DUMBBELL OVERHEAD BY EXTENDING YOUR ELBOWS WHILE EXTENDING YOUR WRISTS. AT THE TOP, HOLD, THEN RETURN TO THE STARTING POSITION IN A CONTROLLED MANNER. REPEAT.",
        "images": ["standing_triceps_extension_0.jpg", "standing_triceps_extension_1.jpg"],
        "video": "STANDING_TRICEPS_EXTENSION.mp4"
    },
    {
        "id": 112,
        "name": "LYING ONE-ARM EXTENSION",
        "description": "MUSCLE GROUP: TRICEPS BRACHII \n STEP 1. LIE ON A BENCH WITH YOUR KNEES BENT FARID FEET FLAT ON THE FLOOR. HOLD A FAIRLY LIGHT DUMBBELL IN YOUR LEFT HAND AND STRAIGHTEN THE ARM SO THAT THE WEIGHT IS ABOVE YOUR SHOULDER. USE YOUR RIGHT HAND TO REACH ACROSS YOUR CHEST AND UP THE UPPER PART OF YOUR LEFT ARM TO HELP STABILIZE IT. \n STEP 2. TURN THE WEIGHT SO THAT YOUR PALM FACES IN. WITHOUT MOVING YOUR UPPER ARM BEND YOUR ELBOW AND SLOWLY LOWER THE DUMBBELL UNTIL IT REACHES THE SIDE OF YOUR HEAD. \n STEP 3. SLOWLY PRESS THE WEIGHT BACK UP ABOVE YOU. FINISH THE SET, THEN SWITCH POSITIONS TO WORK YOUR RIGHT ARM.",
        "images": ["lying_one_arm_extension_0.jpg", "lying_one_arm_extension_1.jpg"],
        "video": "LYING_ONE-ARM_EXTENSION.mp4"
    },
    {
        "id": 113,
        "name": "LYING ONE-ARM EXTENSION SECOND SIDE",
        "description": "MUSCLE GROUP: TRICEPS BRACHII \n STEP 1. LIE ON A BENCH WITH YOUR KNEES BENT FARID FEET FLAT ON THE FLOOR. HOLD A FAIRLY LIGHT DUMBBELL IN YOUR LEFT HAND AND STRAIGHTEN THE ARM SO THAT THE WEIGHT IS ABOVE YOUR SHOULDER. USE YOUR RIGHT HAND TO REACH ACROSS YOUR CHEST AND UP THE UPPER PART OF YOUR LEFT ARM TO HELP STABILIZE IT. \n STEP 2. TURN THE WEIGHT SO THAT YOUR PALM FACES IN. WITHOUT MOVING YOUR UPPER ARM BEND YOUR ELBOW AND SLOWLY LOWER THE DUMBBELL UNTIL IT REACHES THE SIDE OF YOUR HEAD. \n STEP 3. SLOWLY PRESS THE WEIGHT BACK UP ABOVE YOU. FINISH THE SET, THEN SWITCH POSITIONS TO WORK YOUR RIGHT ARM.",
        "images": ["lying_one_arm_extension_right_0.jpg", "lying_one_arm_extension_right_1.jpg"],
        "video": "LYING_ONE-ARM_EXTENSION_right.mp4"
    },
    {
        "id": 114,
        "name": "BODYWEIGHT PUSH-UP INSIDE",
        "description": "MUSCLE GROUP: PECTORALIS \n STEP 1: LIE DOWN CHEST FIRST WITH YOUR HANDS ON THE FLOOR. FORM A DIAMOND SHAPE WITH YOUR HANDS. POSITION HANDS UNDER YOUR LOWER CHEST. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY YOUR HANDS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["bodyweight_push_up_inside_0.jpg", "bodyweight_push_up_inside_1.jpg"],
        "video": "BODYWEIGHT_PUSH-UP_INSIDE.mp4"
    },
    {
        "id": 115,
        "name": "DUMBBELL PUSH-UP ROW 1",
        "description": "MUSCLE GROUP: PECTORALIS \n STEP 1: HOLD ONTO TWO DUMBBELLS WITH NEUTRAL GRIP. DISTANCE BETWEEN YOUR HANDS SHOULD BE SLIGHTLY WIDER THAN SHOULDER WIDTH APART. LIFT YOURSELF WITH YOUR ARMS SO THAT ONLY THE DUMBBELLS AND TOES ARE ON THE FLOOR. MAINTAIN A STRAIGHT BACK. HANDS POINT SLIGHTLY OUTWARD \n STEP 2: LOWER YOURSELF UNTIL YOUR CHEST IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. THE ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND \n STEP 3: RETURN TO STARTING POSITION \n STEP 4: LITU ONE AUMEELL UP DY MOVING YOUR ELBOW UPWARD. YOUR HAND SHOULD MOVE IN A VERTICAL LINE. HOLD FOR ONE SECOND \n STEP 5: RETURN TO STARTING POSITION. \n STEP 6: LOWER IS INCHES AWAY FROM THE FLOOR BY BENDING YOUR ELBOWS. ELBOWS SHOULD BEND TOWARDS YOUR FEET. HOLD FOR ONE SECOND \n STEP 7: RETURN TO STARTING POSITION.",
        "images": ["dumbbell_push_up_row_1_0.jpg", "dumbbell_push_up_row_1_1.jpg", "dumbbell_push_up_row_1_2.jpg"],
        "video": "DUMBBELL_PUSH-UP_ROW_1.mp4"
    },
    {
        "id": 116,
        "name": "BENCH LUNGE",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1. STAND UPRIGHT IN FRONT OF A BENCH WITH YOUR ARMS EXTENDED STRAIGHT DOWNWARD BY YOUR SIDE. THE BENCH SHOULD BE PLACED A COUPLE STEPS IN FRONT OF YOUR STANDING POSITION. \n STEP 2. STEP FORWARD ONTO THE BENCH, LOWERING YOUR BODY DOWNWARD SO THAT YOU HAVE ABEND IN YOUR ONE KNEE, AS ILLUSTRATED \n STEP 3. PUSH OFF OF THAT FOOT TO RETURN TO STARTING POSITION AND REPEAT. TO MAKE THE EXERCISE MORE CHALLENGING, HOLD A PAIR OF DUMBBELLS IN EACH HAND AS YOU PERFORM THE ROUTINE.",
        "images": ["bench_lunge_0.jpg", "bench_lunge_1.jpg"],
        "video": "BENCH_LUNGE.mp4"
    },
    {
        "id": 117,
        "name": "CURL BAR ROW 2",
        "description": "MUSCLE GROUP: LATISSIMUS DORSI \n STEP 1: BEND YOUR KNEES SLIGHTLY. KEEP BACK BENT AND STRAIGHT. HOLD EZ CURL BAR UNDER YOU WITH SHOULDER WIDTH OVERHAND GRIP. \n STEP 2: RAISE THE EZ CURL BAR VERTICALLY TOWARDS YOUR CHEST. REFRAIN FROM FLARING YOUR ELBOWS OUT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["curl_bar_row_2_0.jpg", "curl_bar_row_2_1.jpg"],
        "video": "CURL_BAR_ROW_2.mp4"
    },
    {
        "id": 118,
        "name": "DUMBBELL ROW 2",
        "description": "MUSCLE GROUP: LATISSIMUS DORSI \n STEP 1: KNEEL WITH ONE LEG ON A FLAT BENCH AND PLACE ONE HAND ON THE BENCH FOR SUPPORT. PLACE OTHER LEG ON THE FLOOR AND HOLD DUMBBELL WITH A NEUTRAL GRIP. \n STEP 2: RAISE THE DUMBBELL VERTICALLY TOWARDS YOUR CHEST. REFRAIN FROM FLARING YOUR ELBOW OUT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_row_2_0.jpg", "dumbbell_row_2_1.jpg"],
        "video": "DUMBBELL_ROW_2.mp4"
    },
    {
        "id": 119,
        "name": "DUMBBELL ROW 2 SECOND SIDE",
        "description": "MUSCLE GROUP: LATISSIMUS DORSI \n STEP 1: KNEEL WITH ONE LEG ON A FLAT BENCH AND PLACE ONE HAND ON THE BENCH FOR SUPPORT. PLACE OTHER LEG ON THE FLOOR AND HOLD DUMBBELL WITH A NEUTRAL GRIP. \n STEP 2: RAISE THE DUMBBELL VERTICALLY TOWARDS YOUR CHEST. REFRAIN FROM FLARING YOUR ELBOW OUT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_row_2_right_0.jpg", "dumbbell_row_2_right_1.jpg"],
        "video": "DUMBBELL_ROW_2_right.mp4"
    },
    {
        "id": 120,
        "name": "DUMBBELL BICEPS SEATED CURL",
        "description": "MUSCLE GROUP: BICEPS BRACHII \n STEP 1: WHILE SEATED WITH BACK STRAIGHT, LET DUMBBELLS HANG NEXT TO YOU WITH UNDERHAND GRIP. KEEP ARMS STRAIGHT. \n STEP 2: LIFT DUMBBELLS UP WHILE KEEPING YOUR UPPER ARMS IN PLACE REFRAIN FROM USING YOUR SHOULDERS DURING THE MOVEMENT. HOLD FOR ONE SECOND. RETURN TO STARTING POSITION.",
        "images": ["dumbbell_biceps_seated_curl_0.jpg", "dumbbell_biceps_seated_curl_1.jpg"],
        "video": "DUMBBELL_BICEPS_SEATED_CURL.mp4"
    },
    {
        "id": 121,
        "name": "DUMBBELL BICEPS CURLS ON BENCH",
        "description": "MUSCLE GROUP: BICEPS BRACHII \n STEP 1: WHILE STANDING WITH BACK STRAIGHT, HOLD ONE DUMBBELL WITH NEUTRAL GRIP. REST UPPER ARM ON THE TOP OF THE INCLINE BENCH. \n STEP 2: LIFT DUMBBELL UP WHILE KEEPING YOUR UPPER ARMS IN PLACE. HOLD FOR ONE SECOND. LOWER DUMBBELL BACK TO STARTING POSITION.",
        "images": ["dumbbell_biceps_curls_on_bench_0.jpg", "dumbbell_biceps_curls_on_bench_1.jpg"],
        "video": "DUMBBELL_BICEPS_CURLS_ON_BENCH.mp4"
    },
    {
        "id": 122,
        "name": "DUMBBELL LUNGE PRESS",
        "description": "MUSCLE GROUP: QUADRICEPS \n STEP 1: STAND STRAIGHT WITH FEET SHOULDER WIDTH APART. HOLD DUMBBELLS AT YOUR SIDES WITH NEUTRAL GRIP. \n STEP 2: WHILE KEEPING YOUR BACK STRAIGHT, STEP FORWARD WITH ONE FOOT AND LOWER YOURSELF BY BENDING YOUR KNEES. STOP WHEN YOUR FRONT THIGH IS PARALLEL WITH THE GROUND. HOLD DUMBBELL OVERHEAD WITH ARMS STRAIGHT. STEP BACK AND RETURN TO STARTING POSITION.",
        "images": ["dumbbell_lunge_press_0.jpg", "dumbbell_lunge_press_1.jpg", "dumbbell_lunge_press_2.jpg"],
        "video": "DUMBBELL_LUNGE_PRESS.mp4"
    }
];