export const WORKOUTS = [
    {
        "id": 0,
        "name": "QUICK HIIT",
        "image": "get_lean_quick_hit.jpg",
        "time": 6,
        "exercises": [0, 1, 2, 3],
        "kcal": 80,
        "accessories": "MAT • DUMBBELLS",
        "rounds": 2,
        "duration": 30
    },
    {
        "id": 1,
        "name": "FULL INTENSITY",
        "image": "get_lean_full_intensity_workout.jpg",
        "time": 7,
        "exercises": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        "kcal": 100,
        "accessories": "MAT",
        "rounds": 1,
        "duration": 30
    },
    {
        "id": 2,
        "name": "CIRCUIT BURNER",
        "image": "get_lean_body_sculptor.jpg",
        "time": 15,
        "exercises": [14, 15, 16, 13, 5, 17, 18],
        "kcal": 150,
        "accessories": "MAT • DUMBBELLS • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 3,
        "name": "BOOT CAMP",
        "image": "get_lean_boot_camp.jpg",
        "time": 10,
        "exercises": [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
        "kcal": 130,
        "accessories": "MAT • DUMBBELLS • BENCH",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 4,
        "name": "CORE STRENGTH",
        "image": "get_lean_abs_burner.jpg",
        "time": 7,
        "exercises": [16, 12, 8, 13, 29, 30, 31, 3],
        "kcal": 100,
        "accessories": "MAT",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 5,
        "name": "TOTAL BODY IMPACT",
        "image": "get_lean_total_body_impact.jpg",
        "time": 11,
        "exercises": [4, 25, 32, 16, 9],
        "kcal": 120,
        "accessories": "MAT • DUMBBELLS • BENCH",
        "rounds": 2,
        "duration": 35
    },
    {
        "id": 6,
        "name": "POWER UP",
        "image": "get_strong_power_up.jpg",
        "time": 15,
        "exercises": [20, 15, 33, 34, 3, 14, 10, 13],
        "kcal": 250,
        "accessories": "MAT • DUMBBELLS",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 7,
        "name": "CORE SCULPT",
        "image": "get_strong_core_sculpt.jpg",
        "time": 10,
        "exercises": [30, 8, 31, 12, 35, 29, 16, 3, 36, 37],
        "kcal": 150,
        "accessories": "MAT",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 8,
        "name": "BODY FLEXOR",
        "image": "get_strong_upper_body.jpg",
        "time": 15,
        "exercises": [17, 38, 39, 40, 41, 42, 43, 18],
        "kcal": 280,
        "accessories": "MAT • DUMBBELLS • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 9,
        "name": "LOWER BODY",
        "image": "get_strong_lower_body.jpg",
        "time": 15,
        "exercises": [19, 44, 45, 46, 7, 47, 5, 48],
        "kcal": 230,
        "accessories": "MAT • DUMBBELLS • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 10,
        "name": "FULL BODY WORKOUT",
        "image": "get_strong_full_body_workout.jpg",
        "time": 15,
        "exercises": [2, 34, 27, 14, 18, 0, 49, 3],
        "kcal": 250,
        "accessories": "MAT • BENCH",
        "rounds": 3,
        "duration": 30
    },
    {
        "id": 11,
        "name": "INTENSE INTERVAL",
        "image": "get_strong_intense_interval.jpg",
        "time": 20,
        "exercises": [6, 34, 15, 50, 51, 0, 14, 52, 5, 42],
        "kcal": 280,
        "accessories": "MAT • CHAIR",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 12,
        "name": "TOTAL IMPACT",
        "image": "get_fit_total_impact.jpg",
        "time": 20,
        "exercises": [0, 7, 14, 2, 16, 11, 18, 34, 53],
        "kcal": 300,
        "accessories": "MAT • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 13,
        "name": "FAST CARDIO",
        "image": "get_fit_circuit_challenge.jpg",
        "time": 15,
        "exercises": [6, 54, 10, 8, 34, 55, 25, 0, 4, 5],
        "kcal": 280,
        "accessories": "MAT • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 14,
        "name": "ABS BURNER",
        "image": "get_fit_abs_burner.jpg",
        "time": 8,
        "exercises": [56, 57, 12, 58, 59, 60, 8, 13],
        "kcal": 150,
        "accessories": "MAT • BENCH",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 15,
        "name": "CIRCUIT BREAKER",
        "image": "get_fit_intense_interval_training.jpg",
        "time": 18,
        "exercises": [61, 19, 9, 10, 5],
        "kcal": 270,
        "accessories": "NONE",
        "rounds": 3,
        "duration": 30
    },
    {
        "id": 16,
        "name": "ABS & ARMS",
        "image": "get_fit_extreme_full_body.jpg",
        "time": 15,
        "exercises": [2, 3, 42, 8, 18, 12, 11, 10],
        "kcal": 250,
        "accessories": "MAT • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 17,
        "name": "TABATA WORKOUT",
        "image": "get_fit_tabata_toned_workout.jpg",
        "time": 7,
        "exercises": [6, 5, 0, 11, 61, 14, 9],
        "kcal": 120,
        "accessories": "NONE",
        "rounds": 3,
        "duration": 30
    },
    {
        "id": 18,
        "name": "THE BALANCE OF POWER",
        "image": "get_focused_dinamic_circuit.jpg",
        "time": 7,
        "exercises": [62, 28, 63, 64, 65, 66, 67, 68, 50, 51],
        "kcal": 120,
        "accessories": "MAT • DUMBBELLS",
        "rounds": 1,
        "duration": 30
    },
    {
        "id": 19,
        "name": "CORE CONTROL",
        "image": "get_focused_intense_kick.jpg",
        "time": 6,
        "exercises": [69, 3, 49, 53, 30, 31, 29, 13],
        "kcal": 100,
        "accessories": "MAT • DUMBBELLS",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 20,
        "name": "DYNAMIC CIRCUIT",
        "image": "get_focused_alpha_workout.jpg",
        "time": 10,
        "exercises": [6, 70, 71, 10, 34, 15, 19, 0],
        "kcal": 150,
        "accessories": "MAT • DUMBBELLS",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 21,
        "name": "FOCUS ON ABS",
        "image": "get_focused_quick_abs.jpg",
        "time": 10,
        "exercises": [72, 22, 29, 16, 12, 49, 73, 8, 13, 53],
        "kcal": 170,
        "accessories": "MAT • DUMBBELLS",
        "rounds": 1,
        "duration": 40
    },
    {
        "id": 22,
        "name": "GET POWER",
        "image": "get_focused_get_power.jpg",
        "time": 15,
        "exercises": [74, 32, 75, 1, 76, 77, 42, 18],
        "kcal": 230,
        "accessories": "MAT • DUMBBELLS • BENCH",
        "rounds": 2,
        "duration": 40
    },
    {
        "id": 23,
        "name": "FULL BODY FITNESS",
        "image": "get_focused_extreme_full_body.jpg",
        "time": 12,
        "exercises": [0, 10, 8, 6, 14, 5, 78, 9],
        "kcal": 200,
        "accessories": "MAT • BENCH",
        "rounds": 2,
        "duration": 40
    }
];